System.FormatException: 输入字符串的格式不正确。
   在 System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   在 System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   在 System.Byte.Parse(String s, NumberStyles style, NumberFormatInfo info)
   在 ..(String )
   在 ..(String )
   在 ..(String , String )
   在 ..(String , String )
   在 ..(String )
   在 ..(String , IType )
   在 ..(String , String )
   在 ..(String )
   在 ..( )
   在 ..( , String , String )
   在 ..( , IType )
   在 ..get_Arguments()
   在 ..(ICustomAttribute )
   在 ..(ICustomAttributeCollection )
   在 ..(IMethodDeclaration )
   在 ..(IMethodDeclarationCollection )
   在 ..(ITypeDeclaration )
   在 ..(ITypeDeclaration )
   在 ..TranslateTypeDeclaration(ITypeDeclaration , Boolean , Boolean )
   在 ..WriteTypeDeclaration(ITypeDeclaration , String , ILanguageWriterConfiguration )

