namespace behaviac
{
    using System;

    public static class bt_WrapperAI_Monster_BTMonsterBaozou
    {
        public static bool build_behavior_tree(BehaviorTree bt)
        {
            bt.SetClassNameString("BehaviorTree");
            bt.SetId(-1);
            bt.SetName("WrapperAI/Monster/BTMonsterBaozou");
            bt.AddPar("uint", "p_targetID", "0", string.Empty);
            bt.AddPar("int", "p_srchRange", "0", string.Empty);
            bt.AddPar("uint", "p_selfID", "0", string.Empty);
            bt.AddPar("UnityEngine.Vector3", "p_targetPos", "{kEpsilon=0;x=0;y=0;z=0;}", string.Empty);
            bt.AddPar("int", "p_randomIndex", "0", string.Empty);
            Sequence pChild = new Sequence();
            pChild.SetClassNameString("Sequence");
            pChild.SetId(0);
            bt.AddChild(pChild);
            Assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node4 _node = new Assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node4();
            _node.SetClassNameString("Assignment");
            _node.SetId(4);
            pChild.AddChild(_node);
            pChild.SetHasEvents(pChild.HasEvents() | _node.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node98 _node2 = new Assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node98();
            _node2.SetClassNameString("Assignment");
            _node2.SetId(0x62);
            pChild.AddChild(_node2);
            pChild.SetHasEvents(pChild.HasEvents() | _node2.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node48 _node3 = new Assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node48();
            _node3.SetClassNameString("Assignment");
            _node3.SetId(0x30);
            pChild.AddChild(_node3);
            pChild.SetHasEvents(pChild.HasEvents() | _node3.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node11 _node4 = new Assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node11();
            _node4.SetClassNameString("Assignment");
            _node4.SetId(11);
            pChild.AddChild(_node4);
            pChild.SetHasEvents(pChild.HasEvents() | _node4.HasEvents());
            DecoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node14 _node5 = new DecoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node14();
            _node5.SetClassNameString("DecoratorLoop");
            _node5.SetId(14);
            pChild.AddChild(_node5);
            SelectorLoop loop = new SelectorLoop();
            loop.SetClassNameString("SelectorLoop");
            loop.SetId(1);
            _node5.AddChild(loop);
            WithPrecondition precondition = new WithPrecondition();
            precondition.SetClassNameString("WithPrecondition");
            precondition.SetId(60);
            loop.AddChild(precondition);
            Condition_bt_WrapperAI_Monster_BTMonsterBaozou_node61 _node6 = new Condition_bt_WrapperAI_Monster_BTMonsterBaozou_node61();
            _node6.SetClassNameString("Condition");
            _node6.SetId(0x3d);
            precondition.AddChild(_node6);
            precondition.SetHasEvents(precondition.HasEvents() | _node6.HasEvents());
            IfElse @else = new IfElse();
            @else.SetClassNameString("IfElse");
            @else.SetId(0x10);
            precondition.AddChild(@else);
            Action_bt_WrapperAI_Monster_BTMonsterBaozou_node7 _node7 = new Action_bt_WrapperAI_Monster_BTMonsterBaozou_node7();
            _node7.SetClassNameString("Action");
            _node7.SetId(7);
            @else.AddChild(_node7);
            @else.SetHasEvents(@else.HasEvents() | _node7.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterBaozou_node3 _node8 = new Action_bt_WrapperAI_Monster_BTMonsterBaozou_node3();
            _node8.SetClassNameString("Action");
            _node8.SetId(3);
            @else.AddChild(_node8);
            @else.SetHasEvents(@else.HasEvents() | _node8.HasEvents());
            Sequence sequence2 = new Sequence();
            sequence2.SetClassNameString("Sequence");
            sequence2.SetId(10);
            @else.AddChild(sequence2);
            Action_bt_WrapperAI_Monster_BTMonsterBaozou_node17 _node9 = new Action_bt_WrapperAI_Monster_BTMonsterBaozou_node17();
            _node9.SetClassNameString("Action");
            _node9.SetId(0x11);
            sequence2.AddChild(_node9);
            sequence2.SetHasEvents(sequence2.HasEvents() | _node9.HasEvents());
            IfElse else2 = new IfElse();
            else2.SetClassNameString("IfElse");
            else2.SetId(0x12);
            sequence2.AddChild(else2);
            Condition_bt_WrapperAI_Monster_BTMonsterBaozou_node19 _node10 = new Condition_bt_WrapperAI_Monster_BTMonsterBaozou_node19();
            _node10.SetClassNameString("Condition");
            _node10.SetId(0x13);
            else2.AddChild(_node10);
            else2.SetHasEvents(else2.HasEvents() | _node10.HasEvents());
            Sequence sequence3 = new Sequence();
            sequence3.SetClassNameString("Sequence");
            sequence3.SetId(20);
            else2.AddChild(sequence3);
            Assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node21 _node11 = new Assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node21();
            _node11.SetClassNameString("Assignment");
            _node11.SetId(0x15);
            sequence3.AddChild(_node11);
            sequence3.SetHasEvents(sequence3.HasEvents() | _node11.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node22 _node12 = new Assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node22();
            _node12.SetClassNameString("Assignment");
            _node12.SetId(0x16);
            sequence3.AddChild(_node12);
            sequence3.SetHasEvents(sequence3.HasEvents() | _node12.HasEvents());
            else2.SetHasEvents(else2.HasEvents() | sequence3.HasEvents());
            Noop noop = new Noop();
            noop.SetClassNameString("Noop");
            noop.SetId(0x17);
            else2.AddChild(noop);
            else2.SetHasEvents(else2.HasEvents() | noop.HasEvents());
            sequence2.SetHasEvents(sequence2.HasEvents() | else2.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterBaozou_node26 _node13 = new Action_bt_WrapperAI_Monster_BTMonsterBaozou_node26();
            _node13.SetClassNameString("Action");
            _node13.SetId(0x1a);
            sequence2.AddChild(_node13);
            sequence2.SetHasEvents(sequence2.HasEvents() | _node13.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterBaozou_node27 _node14 = new Action_bt_WrapperAI_Monster_BTMonsterBaozou_node27();
            _node14.SetClassNameString("Action");
            _node14.SetId(0x1b);
            sequence2.AddChild(_node14);
            sequence2.SetHasEvents(sequence2.HasEvents() | _node14.HasEvents());
            @else.SetHasEvents(@else.HasEvents() | sequence2.HasEvents());
            precondition.SetHasEvents(precondition.HasEvents() | @else.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition.HasEvents());
            WithPrecondition precondition2 = new WithPrecondition();
            precondition2.SetClassNameString("WithPrecondition");
            precondition2.SetId(70);
            loop.AddChild(precondition2);
            Condition_bt_WrapperAI_Monster_BTMonsterBaozou_node71 _node15 = new Condition_bt_WrapperAI_Monster_BTMonsterBaozou_node71();
            _node15.SetClassNameString("Condition");
            _node15.SetId(0x47);
            precondition2.AddChild(_node15);
            precondition2.SetHasEvents(precondition2.HasEvents() | _node15.HasEvents());
            IfElse else3 = new IfElse();
            else3.SetClassNameString("IfElse");
            else3.SetId(0x1c);
            precondition2.AddChild(else3);
            Action_bt_WrapperAI_Monster_BTMonsterBaozou_node5 _node16 = new Action_bt_WrapperAI_Monster_BTMonsterBaozou_node5();
            _node16.SetClassNameString("Action");
            _node16.SetId(5);
            else3.AddChild(_node16);
            else3.SetHasEvents(else3.HasEvents() | _node16.HasEvents());
            Sequence sequence4 = new Sequence();
            sequence4.SetClassNameString("Sequence");
            sequence4.SetId(0x1d);
            else3.AddChild(sequence4);
            Action_bt_WrapperAI_Monster_BTMonsterBaozou_node30 _node17 = new Action_bt_WrapperAI_Monster_BTMonsterBaozou_node30();
            _node17.SetClassNameString("Action");
            _node17.SetId(30);
            sequence4.AddChild(_node17);
            sequence4.SetHasEvents(sequence4.HasEvents() | _node17.HasEvents());
            IfElse else4 = new IfElse();
            else4.SetClassNameString("IfElse");
            else4.SetId(0x1f);
            sequence4.AddChild(else4);
            Condition_bt_WrapperAI_Monster_BTMonsterBaozou_node32 _node18 = new Condition_bt_WrapperAI_Monster_BTMonsterBaozou_node32();
            _node18.SetClassNameString("Condition");
            _node18.SetId(0x20);
            else4.AddChild(_node18);
            else4.SetHasEvents(else4.HasEvents() | _node18.HasEvents());
            Sequence sequence5 = new Sequence();
            sequence5.SetClassNameString("Sequence");
            sequence5.SetId(0x21);
            else4.AddChild(sequence5);
            Assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node35 _node19 = new Assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node35();
            _node19.SetClassNameString("Assignment");
            _node19.SetId(0x23);
            sequence5.AddChild(_node19);
            sequence5.SetHasEvents(sequence5.HasEvents() | _node19.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node36 _node20 = new Assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node36();
            _node20.SetClassNameString("Assignment");
            _node20.SetId(0x24);
            sequence5.AddChild(_node20);
            sequence5.SetHasEvents(sequence5.HasEvents() | _node20.HasEvents());
            else4.SetHasEvents(else4.HasEvents() | sequence5.HasEvents());
            Noop noop2 = new Noop();
            noop2.SetClassNameString("Noop");
            noop2.SetId(0x25);
            else4.AddChild(noop2);
            else4.SetHasEvents(else4.HasEvents() | noop2.HasEvents());
            sequence4.SetHasEvents(sequence4.HasEvents() | else4.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterBaozou_node38 _node21 = new Action_bt_WrapperAI_Monster_BTMonsterBaozou_node38();
            _node21.SetClassNameString("Action");
            _node21.SetId(0x26);
            sequence4.AddChild(_node21);
            sequence4.SetHasEvents(sequence4.HasEvents() | _node21.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterBaozou_node39 _node22 = new Action_bt_WrapperAI_Monster_BTMonsterBaozou_node39();
            _node22.SetClassNameString("Action");
            _node22.SetId(0x27);
            sequence4.AddChild(_node22);
            sequence4.SetHasEvents(sequence4.HasEvents() | _node22.HasEvents());
            else3.SetHasEvents(else3.HasEvents() | sequence4.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterBaozou_node6 _node23 = new Action_bt_WrapperAI_Monster_BTMonsterBaozou_node6();
            _node23.SetClassNameString("Action");
            _node23.SetId(6);
            else3.AddChild(_node23);
            else3.SetHasEvents(else3.HasEvents() | _node23.HasEvents());
            precondition2.SetHasEvents(precondition2.HasEvents() | else3.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition2.HasEvents());
            WithPrecondition precondition3 = new WithPrecondition();
            precondition3.SetClassNameString("WithPrecondition");
            precondition3.SetId(0x203);
            loop.AddChild(precondition3);
            Condition_bt_WrapperAI_Monster_BTMonsterBaozou_node516 _node24 = new Condition_bt_WrapperAI_Monster_BTMonsterBaozou_node516();
            _node24.SetClassNameString("Condition");
            _node24.SetId(0x204);
            precondition3.AddChild(_node24);
            precondition3.SetHasEvents(precondition3.HasEvents() | _node24.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterBaozou_node9 _node25 = new Action_bt_WrapperAI_Monster_BTMonsterBaozou_node9();
            _node25.SetClassNameString("Action");
            _node25.SetId(9);
            precondition3.AddChild(_node25);
            precondition3.SetHasEvents(precondition3.HasEvents() | _node25.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition3.HasEvents());
            WithPrecondition precondition4 = new WithPrecondition();
            precondition4.SetClassNameString("WithPrecondition");
            precondition4.SetId(0x18);
            loop.AddChild(precondition4);
            Condition_bt_WrapperAI_Monster_BTMonsterBaozou_node25 _node26 = new Condition_bt_WrapperAI_Monster_BTMonsterBaozou_node25();
            _node26.SetClassNameString("Condition");
            _node26.SetId(0x19);
            precondition4.AddChild(_node26);
            precondition4.SetHasEvents(precondition4.HasEvents() | _node26.HasEvents());
            Sequence sequence6 = new Sequence();
            sequence6.SetClassNameString("Sequence");
            sequence6.SetId(0xa5);
            precondition4.AddChild(sequence6);
            Selector selector = new Selector();
            selector.SetClassNameString("Selector");
            selector.SetId(0x1e7);
            sequence6.AddChild(selector);
            Action_bt_WrapperAI_Monster_BTMonsterBaozou_node488 _node27 = new Action_bt_WrapperAI_Monster_BTMonsterBaozou_node488();
            _node27.SetClassNameString("Action");
            _node27.SetId(0x1e8);
            selector.AddChild(_node27);
            selector.SetHasEvents(selector.HasEvents() | _node27.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterBaozou_node166 _node28 = new Action_bt_WrapperAI_Monster_BTMonsterBaozou_node166();
            _node28.SetClassNameString("Action");
            _node28.SetId(0xa6);
            selector.AddChild(_node28);
            selector.SetHasEvents(selector.HasEvents() | _node28.HasEvents());
            sequence6.SetHasEvents(sequence6.HasEvents() | selector.HasEvents());
            DecoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node167 _node29 = new DecoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node167();
            _node29.SetClassNameString("DecoratorLoop");
            _node29.SetId(0xa7);
            sequence6.AddChild(_node29);
            Noop noop3 = new Noop();
            noop3.SetClassNameString("Noop");
            noop3.SetId(0xa8);
            _node29.AddChild(noop3);
            _node29.SetHasEvents(_node29.HasEvents() | noop3.HasEvents());
            sequence6.SetHasEvents(sequence6.HasEvents() | _node29.HasEvents());
            precondition4.SetHasEvents(precondition4.HasEvents() | sequence6.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition4.HasEvents());
            WithPrecondition precondition5 = new WithPrecondition();
            precondition5.SetClassNameString("WithPrecondition");
            precondition5.SetId(0x22);
            loop.AddChild(precondition5);
            Condition_bt_WrapperAI_Monster_BTMonsterBaozou_node40 _node30 = new Condition_bt_WrapperAI_Monster_BTMonsterBaozou_node40();
            _node30.SetClassNameString("Condition");
            _node30.SetId(40);
            precondition5.AddChild(_node30);
            precondition5.SetHasEvents(precondition5.HasEvents() | _node30.HasEvents());
            Sequence sequence7 = new Sequence();
            sequence7.SetClassNameString("Sequence");
            sequence7.SetId(0x29);
            precondition5.AddChild(sequence7);
            Action_bt_WrapperAI_Monster_BTMonsterBaozou_node42 _node31 = new Action_bt_WrapperAI_Monster_BTMonsterBaozou_node42();
            _node31.SetClassNameString("Action");
            _node31.SetId(0x2a);
            sequence7.AddChild(_node31);
            sequence7.SetHasEvents(sequence7.HasEvents() | _node31.HasEvents());
            DecoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node43 _node32 = new DecoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node43();
            _node32.SetClassNameString("DecoratorLoop");
            _node32.SetId(0x2b);
            sequence7.AddChild(_node32);
            Noop noop4 = new Noop();
            noop4.SetClassNameString("Noop");
            noop4.SetId(0x1ca);
            _node32.AddChild(noop4);
            _node32.SetHasEvents(_node32.HasEvents() | noop4.HasEvents());
            sequence7.SetHasEvents(sequence7.HasEvents() | _node32.HasEvents());
            precondition5.SetHasEvents(precondition5.HasEvents() | sequence7.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition5.HasEvents());
            WithPrecondition precondition6 = new WithPrecondition();
            precondition6.SetClassNameString("WithPrecondition");
            precondition6.SetId(450);
            loop.AddChild(precondition6);
            Condition_bt_WrapperAI_Monster_BTMonsterBaozou_node454 _node33 = new Condition_bt_WrapperAI_Monster_BTMonsterBaozou_node454();
            _node33.SetClassNameString("Condition");
            _node33.SetId(0x1c6);
            precondition6.AddChild(_node33);
            precondition6.SetHasEvents(precondition6.HasEvents() | _node33.HasEvents());
            Sequence sequence8 = new Sequence();
            sequence8.SetClassNameString("Sequence");
            sequence8.SetId(0x1c7);
            precondition6.AddChild(sequence8);
            Action_bt_WrapperAI_Monster_BTMonsterBaozou_node456 _node34 = new Action_bt_WrapperAI_Monster_BTMonsterBaozou_node456();
            _node34.SetClassNameString("Action");
            _node34.SetId(0x1c8);
            sequence8.AddChild(_node34);
            sequence8.SetHasEvents(sequence8.HasEvents() | _node34.HasEvents());
            DecoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node457 _node35 = new DecoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node457();
            _node35.SetClassNameString("DecoratorLoop");
            _node35.SetId(0x1c9);
            sequence8.AddChild(_node35);
            Noop noop5 = new Noop();
            noop5.SetClassNameString("Noop");
            noop5.SetId(2);
            _node35.AddChild(noop5);
            _node35.SetHasEvents(_node35.HasEvents() | noop5.HasEvents());
            sequence8.SetHasEvents(sequence8.HasEvents() | _node35.HasEvents());
            precondition6.SetHasEvents(precondition6.HasEvents() | sequence8.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition6.HasEvents());
            _node5.SetHasEvents(_node5.HasEvents() | loop.HasEvents());
            pChild.SetHasEvents(pChild.HasEvents() | _node5.HasEvents());
            bt.SetHasEvents(bt.HasEvents() | pChild.HasEvents());
            return true;
        }
    }
}

