namespace behaviac
{
    using System;

    public static class bt_WrapperAI_Soldier_BTSoldierSiege
    {
        public static bool build_behavior_tree(BehaviorTree bt)
        {
            bt.SetClassNameString("BehaviorTree");
            bt.SetId(-1);
            bt.SetName("WrapperAI/Soldier/BTSoldierSiege");
            bt.AddPar("Assets.Scripts.GameLogic.SkillSlotType", "p_curSlotType", "SLOT_SKILL_0", string.Empty);
            bt.AddPar("uint", "p_targetID", "0", string.Empty);
            bt.AddPar("int", "p_srchRange", "0", string.Empty);
            bt.AddPar("UnityEngine.Vector3", "p_AttackMoveDest", "{kEpsilon=0;x=0;y=0;z=0;}", string.Empty);
            bt.AddPar("bool", "p_IsAttackMove_Attack", "false", string.Empty);
            bt.AddPar("bool", "p_AttackIsFinished", "true", string.Empty);
            bt.AddPar("uint", "p_CmdID", "0", string.Empty);
            bt.AddPar("UnityEngine.Vector3", "p_attackPathCurTargetPos", "{kEpsilon=0;x=0;y=0;z=0;}", string.Empty);
            bt.AddPar("uint", "p_tempTargetId", "0", string.Empty);
            bt.AddPar("ushort", "p_chooseTargetCount", "0", string.Empty);
            Sequence pChild = new Sequence();
            pChild.SetClassNameString("Sequence");
            pChild.SetId(0);
            bt.AddChild(pChild);
            Assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node106 _node = new Assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node106();
            _node.SetClassNameString("Assignment");
            _node.SetId(0x6a);
            pChild.AddChild(_node);
            pChild.SetHasEvents(pChild.HasEvents() | _node.HasEvents());
            DecoratorLoop_bt_WrapperAI_Soldier_BTSoldierSiege_node14 _node2 = new DecoratorLoop_bt_WrapperAI_Soldier_BTSoldierSiege_node14();
            _node2.SetClassNameString("DecoratorLoop");
            _node2.SetId(14);
            pChild.AddChild(_node2);
            SelectorLoop loop = new SelectorLoop();
            loop.SetClassNameString("SelectorLoop");
            loop.SetId(1);
            _node2.AddChild(loop);
            WithPrecondition precondition = new WithPrecondition();
            precondition.SetClassNameString("WithPrecondition");
            precondition.SetId(0x3b);
            loop.AddChild(precondition);
            Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node78 _node3 = new Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node78();
            _node3.SetClassNameString("Condition");
            _node3.SetId(0x4e);
            precondition.AddChild(_node3);
            precondition.SetHasEvents(precondition.HasEvents() | _node3.HasEvents());
            Sequence sequence2 = new Sequence();
            sequence2.SetClassNameString("Sequence");
            sequence2.SetId(0x29);
            precondition.AddChild(sequence2);
            Assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node42 _node4 = new Assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node42();
            _node4.SetClassNameString("Assignment");
            _node4.SetId(0x2a);
            sequence2.AddChild(_node4);
            sequence2.SetHasEvents(sequence2.HasEvents() | _node4.HasEvents());
            SelectorLoop loop2 = new SelectorLoop();
            loop2.SetClassNameString("SelectorLoop");
            loop2.SetId(0x1d);
            sequence2.AddChild(loop2);
            WithPrecondition precondition2 = new WithPrecondition();
            precondition2.SetClassNameString("WithPrecondition");
            precondition2.SetId(4);
            loop2.AddChild(precondition2);
            Sequence sequence3 = new Sequence();
            sequence3.SetClassNameString("Sequence");
            sequence3.SetId(0x69);
            precondition2.AddChild(sequence3);
            Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node39 _node5 = new Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node39();
            _node5.SetClassNameString("Condition");
            _node5.SetId(0x27);
            sequence3.AddChild(_node5);
            sequence3.SetHasEvents(sequence3.HasEvents() | _node5.HasEvents());
            Compute_bt_WrapperAI_Soldier_BTSoldierSiege_node40 _node6 = new Compute_bt_WrapperAI_Soldier_BTSoldierSiege_node40();
            _node6.SetClassNameString("Compute");
            _node6.SetId(40);
            sequence3.AddChild(_node6);
            sequence3.SetHasEvents(sequence3.HasEvents() | _node6.HasEvents());
            Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node37 _node7 = new Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node37();
            _node7.SetClassNameString("Condition");
            _node7.SetId(0x25);
            sequence3.AddChild(_node7);
            sequence3.SetHasEvents(sequence3.HasEvents() | _node7.HasEvents());
            Assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node107 _node8 = new Assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node107();
            _node8.SetClassNameString("Assignment");
            _node8.SetId(0x6b);
            sequence3.AddChild(_node8);
            sequence3.SetHasEvents(sequence3.HasEvents() | _node8.HasEvents());
            Assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node38 _node9 = new Assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node38();
            _node9.SetClassNameString("Assignment");
            _node9.SetId(0x26);
            sequence3.AddChild(_node9);
            sequence3.SetHasEvents(sequence3.HasEvents() | _node9.HasEvents());
            Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node33 _node10 = new Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node33();
            _node10.SetClassNameString("Condition");
            _node10.SetId(0x21);
            sequence3.AddChild(_node10);
            sequence3.SetHasEvents(sequence3.HasEvents() | _node10.HasEvents());
            Assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node34 _node11 = new Assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node34();
            _node11.SetClassNameString("Assignment");
            _node11.SetId(0x22);
            sequence3.AddChild(_node11);
            sequence3.SetHasEvents(sequence3.HasEvents() | _node11.HasEvents());
            precondition2.SetHasEvents(precondition2.HasEvents() | sequence3.HasEvents());
            False @false = new False();
            @false.SetClassNameString("False");
            @false.SetId(0x24);
            precondition2.AddChild(@false);
            precondition2.SetHasEvents(precondition2.HasEvents() | @false.HasEvents());
            loop2.SetHasEvents(loop2.HasEvents() | precondition2.HasEvents());
            WithPrecondition precondition3 = new WithPrecondition();
            precondition3.SetClassNameString("WithPrecondition");
            precondition3.SetId(30);
            loop2.AddChild(precondition3);
            True @true = new True();
            @true.SetClassNameString("True");
            @true.SetId(0x1f);
            precondition3.AddChild(@true);
            precondition3.SetHasEvents(precondition3.HasEvents() | @true.HasEvents());
            IfElse @else = new IfElse();
            @else.SetClassNameString("IfElse");
            @else.SetId(0x6c);
            precondition3.AddChild(@else);
            Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node109 _node12 = new Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node109();
            _node12.SetClassNameString("Condition");
            _node12.SetId(0x6d);
            @else.AddChild(_node12);
            @else.SetHasEvents(@else.HasEvents() | _node12.HasEvents());
            Sequence sequence4 = new Sequence();
            sequence4.SetClassNameString("Sequence");
            sequence4.SetId(110);
            @else.AddChild(sequence4);
            Action_bt_WrapperAI_Soldier_BTSoldierSiege_node111 _node13 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node111();
            _node13.SetClassNameString("Action");
            _node13.SetId(0x6f);
            sequence4.AddChild(_node13);
            sequence4.SetHasEvents(sequence4.HasEvents() | _node13.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierSiege_node112 _node14 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node112();
            _node14.SetClassNameString("Action");
            _node14.SetId(0x70);
            sequence4.AddChild(_node14);
            sequence4.SetHasEvents(sequence4.HasEvents() | _node14.HasEvents());
            IfElse else2 = new IfElse();
            else2.SetClassNameString("IfElse");
            else2.SetId(5);
            sequence4.AddChild(else2);
            Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node6 _node15 = new Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node6();
            _node15.SetClassNameString("Condition");
            _node15.SetId(6);
            else2.AddChild(_node15);
            else2.SetHasEvents(else2.HasEvents() | _node15.HasEvents());
            Sequence sequence5 = new Sequence();
            sequence5.SetClassNameString("Sequence");
            sequence5.SetId(7);
            else2.AddChild(sequence5);
            Action_bt_WrapperAI_Soldier_BTSoldierSiege_node23 _node16 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node23();
            _node16.SetClassNameString("Action");
            _node16.SetId(0x17);
            sequence5.AddChild(_node16);
            sequence5.SetHasEvents(sequence5.HasEvents() | _node16.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierSiege_node113 _node17 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node113();
            _node17.SetClassNameString("Action");
            _node17.SetId(0x71);
            sequence5.AddChild(_node17);
            sequence5.SetHasEvents(sequence5.HasEvents() | _node17.HasEvents());
            Selector selector = new Selector();
            selector.SetClassNameString("Selector");
            selector.SetId(0x11);
            sequence5.AddChild(selector);
            Action_bt_WrapperAI_Soldier_BTSoldierSiege_node114 _node18 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node114();
            _node18.SetClassNameString("Action");
            _node18.SetId(0x72);
            selector.AddChild(_node18);
            selector.SetHasEvents(selector.HasEvents() | _node18.HasEvents());
            DecoratorAlwaysFailure_bt_WrapperAI_Soldier_BTSoldierSiege_node19 _node19 = new DecoratorAlwaysFailure_bt_WrapperAI_Soldier_BTSoldierSiege_node19();
            _node19.SetClassNameString("DecoratorAlwaysFailure");
            _node19.SetId(0x13);
            selector.AddChild(_node19);
            Assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node18 _node20 = new Assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node18();
            _node20.SetClassNameString("Assignment");
            _node20.SetId(0x12);
            _node19.AddChild(_node20);
            _node19.SetHasEvents(_node19.HasEvents() | _node20.HasEvents());
            selector.SetHasEvents(selector.HasEvents() | _node19.HasEvents());
            sequence5.SetHasEvents(sequence5.HasEvents() | selector.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierSiege_node140 _node21 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node140();
            _node21.SetClassNameString("Action");
            _node21.SetId(140);
            sequence5.AddChild(_node21);
            sequence5.SetHasEvents(sequence5.HasEvents() | _node21.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierSiege_node116 _node22 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node116();
            _node22.SetClassNameString("Action");
            _node22.SetId(0x74);
            sequence5.AddChild(_node22);
            sequence5.SetHasEvents(sequence5.HasEvents() | _node22.HasEvents());
            DecoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierSiege_node117 _node23 = new DecoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierSiege_node117();
            _node23.SetClassNameString("DecoratorLoopUntil");
            _node23.SetId(0x75);
            sequence5.AddChild(_node23);
            Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node118 _node24 = new Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node118();
            _node24.SetClassNameString("Condition");
            _node24.SetId(0x76);
            _node23.AddChild(_node24);
            _node23.SetHasEvents(_node23.HasEvents() | _node24.HasEvents());
            sequence5.SetHasEvents(sequence5.HasEvents() | _node23.HasEvents());
            else2.SetHasEvents(else2.HasEvents() | sequence5.HasEvents());
            Sequence sequence6 = new Sequence();
            sequence6.SetClassNameString("Sequence");
            sequence6.SetId(9);
            else2.AddChild(sequence6);
            Action_bt_WrapperAI_Soldier_BTSoldierSiege_node32 _node25 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node32();
            _node25.SetClassNameString("Action");
            _node25.SetId(0x20);
            sequence6.AddChild(_node25);
            sequence6.SetHasEvents(sequence6.HasEvents() | _node25.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierSiege_node13 _node26 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node13();
            _node26.SetClassNameString("Action");
            _node26.SetId(13);
            sequence6.AddChild(_node26);
            sequence6.SetHasEvents(sequence6.HasEvents() | _node26.HasEvents());
            DecoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierSiege_node15 _node27 = new DecoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierSiege_node15();
            _node27.SetClassNameString("DecoratorLoopUntil");
            _node27.SetId(15);
            sequence6.AddChild(_node27);
            Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node16 _node28 = new Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node16();
            _node28.SetClassNameString("Condition");
            _node28.SetId(0x10);
            _node27.AddChild(_node28);
            _node27.SetHasEvents(_node27.HasEvents() | _node28.HasEvents());
            sequence6.SetHasEvents(sequence6.HasEvents() | _node27.HasEvents());
            else2.SetHasEvents(else2.HasEvents() | sequence6.HasEvents());
            sequence4.SetHasEvents(sequence4.HasEvents() | else2.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierSiege_node28 _node29 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node28();
            _node29.SetClassNameString("Action");
            _node29.SetId(0x1c);
            sequence4.AddChild(_node29);
            sequence4.SetHasEvents(sequence4.HasEvents() | _node29.HasEvents());
            @else.SetHasEvents(@else.HasEvents() | sequence4.HasEvents());
            Sequence sequence7 = new Sequence();
            sequence7.SetClassNameString("Sequence");
            sequence7.SetId(0x80);
            @else.AddChild(sequence7);
            Action_bt_WrapperAI_Soldier_BTSoldierSiege_node129 _node30 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node129();
            _node30.SetClassNameString("Action");
            _node30.SetId(0x81);
            sequence7.AddChild(_node30);
            sequence7.SetHasEvents(sequence7.HasEvents() | _node30.HasEvents());
            IfElse else3 = new IfElse();
            else3.SetClassNameString("IfElse");
            else3.SetId(0x77);
            sequence7.AddChild(else3);
            Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node120 _node31 = new Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node120();
            _node31.SetClassNameString("Condition");
            _node31.SetId(120);
            else3.AddChild(_node31);
            else3.SetHasEvents(else3.HasEvents() | _node31.HasEvents());
            Sequence sequence8 = new Sequence();
            sequence8.SetClassNameString("Sequence");
            sequence8.SetId(0x79);
            else3.AddChild(sequence8);
            Action_bt_WrapperAI_Soldier_BTSoldierSiege_node24 _node32 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node24();
            _node32.SetClassNameString("Action");
            _node32.SetId(0x18);
            sequence8.AddChild(_node32);
            sequence8.SetHasEvents(sequence8.HasEvents() | _node32.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierSiege_node444 _node33 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node444();
            _node33.SetClassNameString("Action");
            _node33.SetId(0x1bc);
            sequence8.AddChild(_node33);
            sequence8.SetHasEvents(sequence8.HasEvents() | _node33.HasEvents());
            Assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node122 _node34 = new Assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node122();
            _node34.SetClassNameString("Assignment");
            _node34.SetId(0x7a);
            sequence8.AddChild(_node34);
            sequence8.SetHasEvents(sequence8.HasEvents() | _node34.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierSiege_node123 _node35 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node123();
            _node35.SetClassNameString("Action");
            _node35.SetId(0x7b);
            sequence8.AddChild(_node35);
            sequence8.SetHasEvents(sequence8.HasEvents() | _node35.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierSiege_node124 _node36 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node124();
            _node36.SetClassNameString("Action");
            _node36.SetId(0x7c);
            sequence8.AddChild(_node36);
            sequence8.SetHasEvents(sequence8.HasEvents() | _node36.HasEvents());
            else3.SetHasEvents(else3.HasEvents() | sequence8.HasEvents());
            Sequence sequence9 = new Sequence();
            sequence9.SetClassNameString("Sequence");
            sequence9.SetId(0x7d);
            else3.AddChild(sequence9);
            Action_bt_WrapperAI_Soldier_BTSoldierSiege_node126 _node37 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node126();
            _node37.SetClassNameString("Action");
            _node37.SetId(0x7e);
            sequence9.AddChild(_node37);
            sequence9.SetHasEvents(sequence9.HasEvents() | _node37.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierSiege_node127 _node38 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node127();
            _node38.SetClassNameString("Action");
            _node38.SetId(0x7f);
            sequence9.AddChild(_node38);
            sequence9.SetHasEvents(sequence9.HasEvents() | _node38.HasEvents());
            else3.SetHasEvents(else3.HasEvents() | sequence9.HasEvents());
            sequence7.SetHasEvents(sequence7.HasEvents() | else3.HasEvents());
            @else.SetHasEvents(@else.HasEvents() | sequence7.HasEvents());
            precondition3.SetHasEvents(precondition3.HasEvents() | @else.HasEvents());
            loop2.SetHasEvents(loop2.HasEvents() | precondition3.HasEvents());
            sequence2.SetHasEvents(sequence2.HasEvents() | loop2.HasEvents());
            precondition.SetHasEvents(precondition.HasEvents() | sequence2.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition.HasEvents());
            WithPrecondition precondition4 = new WithPrecondition();
            precondition4.SetClassNameString("WithPrecondition");
            precondition4.SetId(0x203);
            loop.AddChild(precondition4);
            Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node516 _node39 = new Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node516();
            _node39.SetClassNameString("Condition");
            _node39.SetId(0x204);
            precondition4.AddChild(_node39);
            precondition4.SetHasEvents(precondition4.HasEvents() | _node39.HasEvents());
            Selector selector2 = new Selector();
            selector2.SetClassNameString("Selector");
            selector2.SetId(2);
            precondition4.AddChild(selector2);
            Sequence sequence10 = new Sequence();
            sequence10.SetClassNameString("Sequence");
            sequence10.SetId(3);
            selector2.AddChild(sequence10);
            Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node10 _node40 = new Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node10();
            _node40.SetClassNameString("Condition");
            _node40.SetId(10);
            sequence10.AddChild(_node40);
            sequence10.SetHasEvents(sequence10.HasEvents() | _node40.HasEvents());
            Assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node11 _node41 = new Assignment_bt_WrapperAI_Soldier_BTSoldierSiege_node11();
            _node41.SetClassNameString("Assignment");
            _node41.SetId(11);
            sequence10.AddChild(_node41);
            sequence10.SetHasEvents(sequence10.HasEvents() | _node41.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierSiege_node12 _node42 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node12();
            _node42.SetClassNameString("Action");
            _node42.SetId(12);
            sequence10.AddChild(_node42);
            sequence10.SetHasEvents(sequence10.HasEvents() | _node42.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierSiege_node8 _node43 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node8();
            _node43.SetClassNameString("Action");
            _node43.SetId(8);
            sequence10.AddChild(_node43);
            sequence10.SetHasEvents(sequence10.HasEvents() | _node43.HasEvents());
            selector2.SetHasEvents(selector2.HasEvents() | sequence10.HasEvents());
            Sequence sequence11 = new Sequence();
            sequence11.SetClassNameString("Sequence");
            sequence11.SetId(0x205);
            selector2.AddChild(sequence11);
            Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node20 _node44 = new Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node20();
            _node44.SetClassNameString("Condition");
            _node44.SetId(20);
            sequence11.AddChild(_node44);
            sequence11.SetHasEvents(sequence11.HasEvents() | _node44.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierSiege_node518 _node45 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node518();
            _node45.SetClassNameString("Action");
            _node45.SetId(0x206);
            sequence11.AddChild(_node45);
            sequence11.SetHasEvents(sequence11.HasEvents() | _node45.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierSiege_node519 _node46 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node519();
            _node46.SetClassNameString("Action");
            _node46.SetId(0x207);
            sequence11.AddChild(_node46);
            sequence11.SetHasEvents(sequence11.HasEvents() | _node46.HasEvents());
            IfElse else4 = new IfElse();
            else4.SetClassNameString("IfElse");
            else4.SetId(520);
            sequence11.AddChild(else4);
            Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node521 _node47 = new Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node521();
            _node47.SetClassNameString("Condition");
            _node47.SetId(0x209);
            else4.AddChild(_node47);
            else4.SetHasEvents(else4.HasEvents() | _node47.HasEvents());
            Sequence sequence12 = new Sequence();
            sequence12.SetClassNameString("Sequence");
            sequence12.SetId(0x20a);
            else4.AddChild(sequence12);
            Action_bt_WrapperAI_Soldier_BTSoldierSiege_node523 _node48 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node523();
            _node48.SetClassNameString("Action");
            _node48.SetId(0x20b);
            sequence12.AddChild(_node48);
            sequence12.SetHasEvents(sequence12.HasEvents() | _node48.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierSiege_node524 _node49 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node524();
            _node49.SetClassNameString("Action");
            _node49.SetId(0x20c);
            sequence12.AddChild(_node49);
            sequence12.SetHasEvents(sequence12.HasEvents() | _node49.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierSiege_node526 _node50 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node526();
            _node50.SetClassNameString("Action");
            _node50.SetId(0x20e);
            sequence12.AddChild(_node50);
            sequence12.SetHasEvents(sequence12.HasEvents() | _node50.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierSiege_node25 _node51 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node25();
            _node51.SetClassNameString("Action");
            _node51.SetId(0x19);
            sequence12.AddChild(_node51);
            sequence12.SetHasEvents(sequence12.HasEvents() | _node51.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierSiege_node530 _node52 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node530();
            _node52.SetClassNameString("Action");
            _node52.SetId(530);
            sequence12.AddChild(_node52);
            sequence12.SetHasEvents(sequence12.HasEvents() | _node52.HasEvents());
            DecoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierSiege_node531 _node53 = new DecoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierSiege_node531();
            _node53.SetClassNameString("DecoratorLoopUntil");
            _node53.SetId(0x213);
            sequence12.AddChild(_node53);
            Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node532 _node54 = new Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node532();
            _node54.SetClassNameString("Condition");
            _node54.SetId(0x214);
            _node53.AddChild(_node54);
            _node53.SetHasEvents(_node53.HasEvents() | _node54.HasEvents());
            sequence12.SetHasEvents(sequence12.HasEvents() | _node53.HasEvents());
            else4.SetHasEvents(else4.HasEvents() | sequence12.HasEvents());
            Sequence sequence13 = new Sequence();
            sequence13.SetClassNameString("Sequence");
            sequence13.SetId(0x215);
            else4.AddChild(sequence13);
            Action_bt_WrapperAI_Soldier_BTSoldierSiege_node26 _node55 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node26();
            _node55.SetClassNameString("Action");
            _node55.SetId(0x1a);
            sequence13.AddChild(_node55);
            sequence13.SetHasEvents(sequence13.HasEvents() | _node55.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierSiege_node535 _node56 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node535();
            _node56.SetClassNameString("Action");
            _node56.SetId(0x217);
            sequence13.AddChild(_node56);
            sequence13.SetHasEvents(sequence13.HasEvents() | _node56.HasEvents());
            DecoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierSiege_node536 _node57 = new DecoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierSiege_node536();
            _node57.SetClassNameString("DecoratorLoopUntil");
            _node57.SetId(0x218);
            sequence13.AddChild(_node57);
            Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node537 _node58 = new Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node537();
            _node58.SetClassNameString("Condition");
            _node58.SetId(0x219);
            _node57.AddChild(_node58);
            _node57.SetHasEvents(_node57.HasEvents() | _node58.HasEvents());
            sequence13.SetHasEvents(sequence13.HasEvents() | _node57.HasEvents());
            else4.SetHasEvents(else4.HasEvents() | sequence13.HasEvents());
            sequence11.SetHasEvents(sequence11.HasEvents() | else4.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierSiege_node538 _node59 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node538();
            _node59.SetClassNameString("Action");
            _node59.SetId(0x21a);
            sequence11.AddChild(_node59);
            sequence11.SetHasEvents(sequence11.HasEvents() | _node59.HasEvents());
            selector2.SetHasEvents(selector2.HasEvents() | sequence11.HasEvents());
            precondition4.SetHasEvents(precondition4.HasEvents() | selector2.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition4.HasEvents());
            WithPrecondition precondition5 = new WithPrecondition();
            precondition5.SetClassNameString("WithPrecondition");
            precondition5.SetId(0x15);
            loop.AddChild(precondition5);
            Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node22 _node60 = new Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node22();
            _node60.SetClassNameString("Condition");
            _node60.SetId(0x16);
            precondition5.AddChild(_node60);
            precondition5.SetHasEvents(precondition5.HasEvents() | _node60.HasEvents());
            Sequence sequence14 = new Sequence();
            sequence14.SetClassNameString("Sequence");
            sequence14.SetId(0x1b);
            precondition5.AddChild(sequence14);
            Selector selector3 = new Selector();
            selector3.SetClassNameString("Selector");
            selector3.SetId(0x1e7);
            sequence14.AddChild(selector3);
            Action_bt_WrapperAI_Soldier_BTSoldierSiege_node488 _node61 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node488();
            _node61.SetClassNameString("Action");
            _node61.SetId(0x1e8);
            selector3.AddChild(_node61);
            selector3.SetHasEvents(selector3.HasEvents() | _node61.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierSiege_node35 _node62 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node35();
            _node62.SetClassNameString("Action");
            _node62.SetId(0x23);
            selector3.AddChild(_node62);
            selector3.SetHasEvents(selector3.HasEvents() | _node62.HasEvents());
            sequence14.SetHasEvents(sequence14.HasEvents() | selector3.HasEvents());
            DecoratorLoop_bt_WrapperAI_Soldier_BTSoldierSiege_node65 _node63 = new DecoratorLoop_bt_WrapperAI_Soldier_BTSoldierSiege_node65();
            _node63.SetClassNameString("DecoratorLoop");
            _node63.SetId(0x41);
            sequence14.AddChild(_node63);
            Noop noop = new Noop();
            noop.SetClassNameString("Noop");
            noop.SetId(0x42);
            _node63.AddChild(noop);
            _node63.SetHasEvents(_node63.HasEvents() | noop.HasEvents());
            sequence14.SetHasEvents(sequence14.HasEvents() | _node63.HasEvents());
            precondition5.SetHasEvents(precondition5.HasEvents() | sequence14.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition5.HasEvents());
            WithPrecondition precondition6 = new WithPrecondition();
            precondition6.SetClassNameString("WithPrecondition");
            precondition6.SetId(450);
            loop.AddChild(precondition6);
            Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node454 _node64 = new Condition_bt_WrapperAI_Soldier_BTSoldierSiege_node454();
            _node64.SetClassNameString("Condition");
            _node64.SetId(0x1c6);
            precondition6.AddChild(_node64);
            precondition6.SetHasEvents(precondition6.HasEvents() | _node64.HasEvents());
            Sequence sequence15 = new Sequence();
            sequence15.SetClassNameString("Sequence");
            sequence15.SetId(0x1c7);
            precondition6.AddChild(sequence15);
            Action_bt_WrapperAI_Soldier_BTSoldierSiege_node456 _node65 = new Action_bt_WrapperAI_Soldier_BTSoldierSiege_node456();
            _node65.SetClassNameString("Action");
            _node65.SetId(0x1c8);
            sequence15.AddChild(_node65);
            sequence15.SetHasEvents(sequence15.HasEvents() | _node65.HasEvents());
            DecoratorLoop_bt_WrapperAI_Soldier_BTSoldierSiege_node457 _node66 = new DecoratorLoop_bt_WrapperAI_Soldier_BTSoldierSiege_node457();
            _node66.SetClassNameString("DecoratorLoop");
            _node66.SetId(0x1c9);
            sequence15.AddChild(_node66);
            Noop noop2 = new Noop();
            noop2.SetClassNameString("Noop");
            noop2.SetId(0x1ca);
            _node66.AddChild(noop2);
            _node66.SetHasEvents(_node66.HasEvents() | noop2.HasEvents());
            sequence15.SetHasEvents(sequence15.HasEvents() | _node66.HasEvents());
            precondition6.SetHasEvents(precondition6.HasEvents() | sequence15.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition6.HasEvents());
            _node2.SetHasEvents(_node2.HasEvents() | loop.HasEvents());
            pChild.SetHasEvents(pChild.HasEvents() | _node2.HasEvents());
            bt.SetHasEvents(bt.HasEvents() | pChild.HasEvents());
            return true;
        }
    }
}

