namespace behaviac
{
    using System;

    public static class bt_WrapperAI_Monster_BTMonsterPassive
    {
        public static bool build_behavior_tree(BehaviorTree bt)
        {
            bt.SetClassNameString("BehaviorTree");
            bt.SetId(-1);
            bt.SetName("WrapperAI/Monster/BTMonsterPassive");
            bt.AddPar("Assets.Scripts.GameLogic.SkillSlotType", "p_curSlotType", "SLOT_SKILL_0", string.Empty);
            bt.AddPar("uint", "p_targetID", "0", string.Empty);
            bt.AddPar("int", "p_srchRange", "0", string.Empty);
            bt.AddPar("UnityEngine.Vector3", "p_AttackMoveDest", "{kEpsilon=0;x=0;y=0;z=0;}", string.Empty);
            bt.AddPar("bool", "p_IsAttackMove_Attack", "false", string.Empty);
            bt.AddPar("bool", "p_AttackIsFinished", "true", string.Empty);
            bt.AddPar("uint", "p_CmdID", "0", string.Empty);
            bt.AddPar("UnityEngine.Vector3", "p_attackPathCurTargetPos", "{kEpsilon=0;x=0;y=0;z=0;}", string.Empty);
            bt.AddPar("int", "p_skillAttackRange", "0", string.Empty);
            bt.AddPar("UnityEngine.Vector3", "p_orignalPos", "{kEpsilon=0;x=0;y=0;z=0;}", string.Empty);
            bt.AddPar("int", "p_follow_range", "9000", string.Empty);
            bt.AddPar("UnityEngine.Vector3", "p_orignalDirection", "{kEpsilon=0;x=0;y=0;z=0;}", string.Empty);
            bt.AddPar("int", "p_pursuitRange", "0", string.Empty);
            bt.AddPar("int", "p_waitFramesToSearch", "10", string.Empty);
            bt.AddPar("uint", "p_selfID", "0", string.Empty);
            bt.AddPar("int", "p_attackOneTime", "0", string.Empty);
            bt.AddPar("uint", "p_terrorMeActor", "0", string.Empty);
            Sequence pChild = new Sequence();
            pChild.SetClassNameString("Sequence");
            pChild.SetId(0);
            bt.AddChild(pChild);
            Assignment_bt_WrapperAI_Monster_BTMonsterPassive_node98 _node = new Assignment_bt_WrapperAI_Monster_BTMonsterPassive_node98();
            _node.SetClassNameString("Assignment");
            _node.SetId(0x62);
            pChild.AddChild(_node);
            pChild.SetHasEvents(pChild.HasEvents() | _node.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterPassive_node20 _node2 = new Assignment_bt_WrapperAI_Monster_BTMonsterPassive_node20();
            _node2.SetClassNameString("Assignment");
            _node2.SetId(20);
            pChild.AddChild(_node2);
            pChild.SetHasEvents(pChild.HasEvents() | _node2.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterPassive_node31 _node3 = new Assignment_bt_WrapperAI_Monster_BTMonsterPassive_node31();
            _node3.SetClassNameString("Assignment");
            _node3.SetId(0x1f);
            pChild.AddChild(_node3);
            pChild.SetHasEvents(pChild.HasEvents() | _node3.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterPassive_node48 _node4 = new Assignment_bt_WrapperAI_Monster_BTMonsterPassive_node48();
            _node4.SetClassNameString("Assignment");
            _node4.SetId(0x30);
            pChild.AddChild(_node4);
            pChild.SetHasEvents(pChild.HasEvents() | _node4.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterPassive_node11 _node5 = new Assignment_bt_WrapperAI_Monster_BTMonsterPassive_node11();
            _node5.SetClassNameString("Assignment");
            _node5.SetId(11);
            pChild.AddChild(_node5);
            pChild.SetHasEvents(pChild.HasEvents() | _node5.HasEvents());
            DecoratorLoop_bt_WrapperAI_Monster_BTMonsterPassive_node14 _node6 = new DecoratorLoop_bt_WrapperAI_Monster_BTMonsterPassive_node14();
            _node6.SetClassNameString("DecoratorLoop");
            _node6.SetId(14);
            pChild.AddChild(_node6);
            SelectorLoop loop = new SelectorLoop();
            loop.SetClassNameString("SelectorLoop");
            loop.SetId(1);
            _node6.AddChild(loop);
            WithPrecondition precondition = new WithPrecondition();
            precondition.SetClassNameString("WithPrecondition");
            precondition.SetId(60);
            loop.AddChild(precondition);
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node61 _node7 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node61();
            _node7.SetClassNameString("Condition");
            _node7.SetId(0x3d);
            precondition.AddChild(_node7);
            precondition.SetHasEvents(precondition.HasEvents() | _node7.HasEvents());
            Sequence sequence2 = new Sequence();
            sequence2.SetClassNameString("Sequence");
            sequence2.SetId(0x2e);
            precondition.AddChild(sequence2);
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node47 _node8 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node47();
            _node8.SetClassNameString("Action");
            _node8.SetId(0x2f);
            sequence2.AddChild(_node8);
            sequence2.SetHasEvents(sequence2.HasEvents() | _node8.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node161 _node9 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node161();
            _node9.SetClassNameString("Action");
            _node9.SetId(0xa1);
            sequence2.AddChild(_node9);
            sequence2.SetHasEvents(sequence2.HasEvents() | _node9.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node174 _node10 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node174();
            _node10.SetClassNameString("Action");
            _node10.SetId(0xae);
            sequence2.AddChild(_node10);
            sequence2.SetHasEvents(sequence2.HasEvents() | _node10.HasEvents());
            IfElse @else = new IfElse();
            @else.SetClassNameString("IfElse");
            @else.SetId(0xf5);
            sequence2.AddChild(@else);
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node246 _node11 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node246();
            _node11.SetClassNameString("Condition");
            _node11.SetId(0xf6);
            @else.AddChild(_node11);
            @else.SetHasEvents(@else.HasEvents() | _node11.HasEvents());
            IfElse else2 = new IfElse();
            else2.SetClassNameString("IfElse");
            else2.SetId(0x1b);
            @else.AddChild(else2);
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node28 _node12 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node28();
            _node12.SetClassNameString("Condition");
            _node12.SetId(0x1c);
            else2.AddChild(_node12);
            else2.SetHasEvents(else2.HasEvents() | _node12.HasEvents());
            Sequence sequence3 = new Sequence();
            sequence3.SetClassNameString("Sequence");
            sequence3.SetId(0xf7);
            else2.AddChild(sequence3);
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node248 _node13 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node248();
            _node13.SetClassNameString("Action");
            _node13.SetId(0xf8);
            sequence3.AddChild(_node13);
            sequence3.SetHasEvents(sequence3.HasEvents() | _node13.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node21 _node14 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node21();
            _node14.SetClassNameString("Action");
            _node14.SetId(0x15);
            sequence3.AddChild(_node14);
            sequence3.SetHasEvents(sequence3.HasEvents() | _node14.HasEvents());
            DecoratorLoop_bt_WrapperAI_Monster_BTMonsterPassive_node66 _node15 = new DecoratorLoop_bt_WrapperAI_Monster_BTMonsterPassive_node66();
            _node15.SetClassNameString("DecoratorLoop");
            _node15.SetId(0x42);
            sequence3.AddChild(_node15);
            Sequence sequence4 = new Sequence();
            sequence4.SetClassNameString("Sequence");
            sequence4.SetId(7);
            _node15.AddChild(sequence4);
            Selector selector = new Selector();
            selector.SetClassNameString("Selector");
            selector.SetId(0x43);
            sequence4.AddChild(selector);
            Sequence sequence5 = new Sequence();
            sequence5.SetClassNameString("Sequence");
            sequence5.SetId(0x44);
            selector.AddChild(sequence5);
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node69 _node16 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node69();
            _node16.SetClassNameString("Condition");
            _node16.SetId(0x45);
            sequence5.AddChild(_node16);
            sequence5.SetHasEvents(sequence5.HasEvents() | _node16.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node231 _node17 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node231();
            _node17.SetClassNameString("Action");
            _node17.SetId(0xe7);
            sequence5.AddChild(_node17);
            sequence5.SetHasEvents(sequence5.HasEvents() | _node17.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node232 _node18 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node232();
            _node18.SetClassNameString("Action");
            _node18.SetId(0xe8);
            sequence5.AddChild(_node18);
            sequence5.SetHasEvents(sequence5.HasEvents() | _node18.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node233 _node19 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node233();
            _node19.SetClassNameString("Action");
            _node19.SetId(0xe9);
            sequence5.AddChild(_node19);
            sequence5.SetHasEvents(sequence5.HasEvents() | _node19.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterPassive_node234 _node20 = new Assignment_bt_WrapperAI_Monster_BTMonsterPassive_node234();
            _node20.SetClassNameString("Assignment");
            _node20.SetId(0xea);
            sequence5.AddChild(_node20);
            sequence5.SetHasEvents(sequence5.HasEvents() | _node20.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node32 _node21 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node32();
            _node21.SetClassNameString("Action");
            _node21.SetId(0x20);
            sequence5.AddChild(_node21);
            sequence5.SetHasEvents(sequence5.HasEvents() | _node21.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node13 _node22 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node13();
            _node22.SetClassNameString("Action");
            _node22.SetId(13);
            sequence5.AddChild(_node22);
            sequence5.SetHasEvents(sequence5.HasEvents() | _node22.HasEvents());
            selector.SetHasEvents(selector.HasEvents() | sequence5.HasEvents());
            Sequence sequence6 = new Sequence();
            sequence6.SetClassNameString("Sequence");
            sequence6.SetId(0xeb);
            selector.AddChild(sequence6);
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node236 _node23 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node236();
            _node23.SetClassNameString("Condition");
            _node23.SetId(0xec);
            sequence6.AddChild(_node23);
            sequence6.SetHasEvents(sequence6.HasEvents() | _node23.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node237 _node24 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node237();
            _node24.SetClassNameString("Action");
            _node24.SetId(0xed);
            sequence6.AddChild(_node24);
            sequence6.SetHasEvents(sequence6.HasEvents() | _node24.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node238 _node25 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node238();
            _node25.SetClassNameString("Action");
            _node25.SetId(0xee);
            sequence6.AddChild(_node25);
            sequence6.SetHasEvents(sequence6.HasEvents() | _node25.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterPassive_node239 _node26 = new Assignment_bt_WrapperAI_Monster_BTMonsterPassive_node239();
            _node26.SetClassNameString("Assignment");
            _node26.SetId(0xef);
            sequence6.AddChild(_node26);
            sequence6.SetHasEvents(sequence6.HasEvents() | _node26.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node15 _node27 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node15();
            _node27.SetClassNameString("Action");
            _node27.SetId(15);
            sequence6.AddChild(_node27);
            sequence6.SetHasEvents(sequence6.HasEvents() | _node27.HasEvents());
            selector.SetHasEvents(selector.HasEvents() | sequence6.HasEvents());
            sequence4.SetHasEvents(sequence4.HasEvents() | selector.HasEvents());
            WaitFrames_bt_WrapperAI_Monster_BTMonsterPassive_node8 _node28 = new WaitFrames_bt_WrapperAI_Monster_BTMonsterPassive_node8();
            _node28.SetClassNameString("WaitFrames");
            _node28.SetId(8);
            sequence4.AddChild(_node28);
            sequence4.SetHasEvents(sequence4.HasEvents() | _node28.HasEvents());
            _node15.SetHasEvents(_node15.HasEvents() | sequence4.HasEvents());
            sequence3.SetHasEvents(sequence3.HasEvents() | _node15.HasEvents());
            else2.SetHasEvents(else2.HasEvents() | sequence3.HasEvents());
            Noop noop = new Noop();
            noop.SetClassNameString("Noop");
            noop.SetId(0x1d);
            else2.AddChild(noop);
            else2.SetHasEvents(else2.HasEvents() | noop.HasEvents());
            @else.SetHasEvents(@else.HasEvents() | else2.HasEvents());
            Sequence sequence7 = new Sequence();
            sequence7.SetClassNameString("Sequence");
            sequence7.SetId(0xff);
            @else.AddChild(sequence7);
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node19 _node29 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node19();
            _node29.SetClassNameString("Action");
            _node29.SetId(0x13);
            sequence7.AddChild(_node29);
            sequence7.SetHasEvents(sequence7.HasEvents() | _node29.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node256 _node30 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node256();
            _node30.SetClassNameString("Action");
            _node30.SetId(0x100);
            sequence7.AddChild(_node30);
            sequence7.SetHasEvents(sequence7.HasEvents() | _node30.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node257 _node31 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node257();
            _node31.SetClassNameString("Action");
            _node31.SetId(0x101);
            sequence7.AddChild(_node31);
            sequence7.SetHasEvents(sequence7.HasEvents() | _node31.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node148 _node32 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node148();
            _node32.SetClassNameString("Action");
            _node32.SetId(0x94);
            sequence7.AddChild(_node32);
            sequence7.SetHasEvents(sequence7.HasEvents() | _node32.HasEvents());
            @else.SetHasEvents(@else.HasEvents() | sequence7.HasEvents());
            sequence2.SetHasEvents(sequence2.HasEvents() | @else.HasEvents());
            precondition.SetHasEvents(precondition.HasEvents() | sequence2.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition.HasEvents());
            WithPrecondition precondition2 = new WithPrecondition();
            precondition2.SetClassNameString("WithPrecondition");
            precondition2.SetId(70);
            loop.AddChild(precondition2);
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node71 _node33 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node71();
            _node33.SetClassNameString("Condition");
            _node33.SetId(0x47);
            precondition2.AddChild(_node33);
            precondition2.SetHasEvents(precondition2.HasEvents() | _node33.HasEvents());
            Selector selector2 = new Selector();
            selector2.SetClassNameString("Selector");
            selector2.SetId(0x12);
            precondition2.AddChild(selector2);
            Sequence sequence8 = new Sequence();
            sequence8.SetClassNameString("Sequence");
            sequence8.SetId(0xa2);
            selector2.AddChild(sequence8);
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node163 _node34 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node163();
            _node34.SetClassNameString("Condition");
            _node34.SetId(0xa3);
            sequence8.AddChild(_node34);
            sequence8.SetHasEvents(sequence8.HasEvents() | _node34.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node72 _node35 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node72();
            _node35.SetClassNameString("Action");
            _node35.SetId(0x48);
            sequence8.AddChild(_node35);
            sequence8.SetHasEvents(sequence8.HasEvents() | _node35.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node167 _node36 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node167();
            _node36.SetClassNameString("Action");
            _node36.SetId(0xa7);
            sequence8.AddChild(_node36);
            sequence8.SetHasEvents(sequence8.HasEvents() | _node36.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node173 _node37 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node173();
            _node37.SetClassNameString("Action");
            _node37.SetId(0xad);
            sequence8.AddChild(_node37);
            sequence8.SetHasEvents(sequence8.HasEvents() | _node37.HasEvents());
            selector2.SetHasEvents(selector2.HasEvents() | sequence8.HasEvents());
            IfElse else3 = new IfElse();
            else3.SetClassNameString("IfElse");
            else3.SetId(0x18);
            selector2.AddChild(else3);
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node166 _node38 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node166();
            _node38.SetClassNameString("Condition");
            _node38.SetId(0xa6);
            else3.AddChild(_node38);
            else3.SetHasEvents(else3.HasEvents() | _node38.HasEvents());
            IfElse else4 = new IfElse();
            else4.SetClassNameString("IfElse");
            else4.SetId(170);
            else3.AddChild(else4);
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node130 _node39 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node130();
            _node39.SetClassNameString("Condition");
            _node39.SetId(130);
            else4.AddChild(_node39);
            else4.SetHasEvents(else4.HasEvents() | _node39.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node164 _node40 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node164();
            _node40.SetClassNameString("Action");
            _node40.SetId(0xa4);
            else4.AddChild(_node40);
            else4.SetHasEvents(else4.HasEvents() | _node40.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node172 _node41 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node172();
            _node41.SetClassNameString("Action");
            _node41.SetId(0xac);
            else4.AddChild(_node41);
            else4.SetHasEvents(else4.HasEvents() | _node41.HasEvents());
            else3.SetHasEvents(else3.HasEvents() | else4.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node169 _node42 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node169();
            _node42.SetClassNameString("Action");
            _node42.SetId(0xa9);
            else3.AddChild(_node42);
            else3.SetHasEvents(else3.HasEvents() | _node42.HasEvents());
            selector2.SetHasEvents(selector2.HasEvents() | else3.HasEvents());
            Sequence sequence9 = new Sequence();
            sequence9.SetClassNameString("Sequence");
            sequence9.SetId(0x4b);
            selector2.AddChild(sequence9);
            IfElse else5 = new IfElse();
            else5.SetClassNameString("IfElse");
            else5.SetId(0x4d);
            sequence9.AddChild(else5);
            Sequence sequence10 = new Sequence();
            sequence10.SetClassNameString("Sequence");
            sequence10.SetId(0x24);
            else5.AddChild(sequence10);
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node100 _node43 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node100();
            _node43.SetClassNameString("Condition");
            _node43.SetId(100);
            sequence10.AddChild(_node43);
            sequence10.SetHasEvents(sequence10.HasEvents() | _node43.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node35 _node44 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node35();
            _node44.SetClassNameString("Condition");
            _node44.SetId(0x23);
            sequence10.AddChild(_node44);
            sequence10.SetHasEvents(sequence10.HasEvents() | _node44.HasEvents());
            else5.SetHasEvents(else5.HasEvents() | sequence10.HasEvents());
            Noop noop2 = new Noop();
            noop2.SetClassNameString("Noop");
            noop2.SetId(0x83);
            else5.AddChild(noop2);
            else5.SetHasEvents(else5.HasEvents() | noop2.HasEvents());
            Sequence sequence11 = new Sequence();
            sequence11.SetClassNameString("Sequence");
            sequence11.SetId(0x10);
            else5.AddChild(sequence11);
            Assignment_bt_WrapperAI_Monster_BTMonsterPassive_node133 _node45 = new Assignment_bt_WrapperAI_Monster_BTMonsterPassive_node133();
            _node45.SetClassNameString("Assignment");
            _node45.SetId(0x85);
            sequence11.AddChild(_node45);
            sequence11.SetHasEvents(sequence11.HasEvents() | _node45.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterPassive_node33 _node46 = new Assignment_bt_WrapperAI_Monster_BTMonsterPassive_node33();
            _node46.SetClassNameString("Assignment");
            _node46.SetId(0x21);
            sequence11.AddChild(_node46);
            sequence11.SetHasEvents(sequence11.HasEvents() | _node46.HasEvents());
            else5.SetHasEvents(else5.HasEvents() | sequence11.HasEvents());
            sequence9.SetHasEvents(sequence9.HasEvents() | else5.HasEvents());
            Compute_bt_WrapperAI_Monster_BTMonsterPassive_node6 _node47 = new Compute_bt_WrapperAI_Monster_BTMonsterPassive_node6();
            _node47.SetClassNameString("Compute");
            _node47.SetId(6);
            sequence9.AddChild(_node47);
            sequence9.SetHasEvents(sequence9.HasEvents() | _node47.HasEvents());
            IfElse else6 = new IfElse();
            else6.SetClassNameString("IfElse");
            else6.SetId(0x86);
            sequence9.AddChild(else6);
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node5 _node48 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node5();
            _node48.SetClassNameString("Condition");
            _node48.SetId(5);
            else6.AddChild(_node48);
            else6.SetHasEvents(else6.HasEvents() | _node48.HasEvents());
            Sequence sequence12 = new Sequence();
            sequence12.SetClassNameString("Sequence");
            sequence12.SetId(0x89);
            else6.AddChild(sequence12);
            Selector selector3 = new Selector();
            selector3.SetClassNameString("Selector");
            selector3.SetId(0x8a);
            sequence12.AddChild(selector3);
            Sequence sequence13 = new Sequence();
            sequence13.SetClassNameString("Sequence");
            sequence13.SetId(0x8b);
            selector3.AddChild(sequence13);
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node156 _node49 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node156();
            _node49.SetClassNameString("Action");
            _node49.SetId(0x9c);
            sequence13.AddChild(_node49);
            sequence13.SetHasEvents(sequence13.HasEvents() | _node49.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterPassive_node159 _node50 = new Assignment_bt_WrapperAI_Monster_BTMonsterPassive_node159();
            _node50.SetClassNameString("Assignment");
            _node50.SetId(0x9f);
            sequence13.AddChild(_node50);
            sequence13.SetHasEvents(sequence13.HasEvents() | _node50.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterPassive_node160 _node51 = new Assignment_bt_WrapperAI_Monster_BTMonsterPassive_node160();
            _node51.SetClassNameString("Assignment");
            _node51.SetId(160);
            sequence13.AddChild(_node51);
            sequence13.SetHasEvents(sequence13.HasEvents() | _node51.HasEvents());
            Selector selector4 = new Selector();
            selector4.SetClassNameString("Selector");
            selector4.SetId(0x6f);
            sequence13.AddChild(selector4);
            Sequence sequence14 = new Sequence();
            sequence14.SetClassNameString("Sequence");
            sequence14.SetId(0x76);
            selector4.AddChild(sequence14);
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node712 _node52 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node712();
            _node52.SetClassNameString("Action");
            _node52.SetId(0x2c8);
            sequence14.AddChild(_node52);
            sequence14.SetHasEvents(sequence14.HasEvents() | _node52.HasEvents());
            Selector selector5 = new Selector();
            selector5.SetClassNameString("Selector");
            selector5.SetId(3);
            sequence14.AddChild(selector5);
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node2 _node53 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node2();
            _node53.SetClassNameString("Condition");
            _node53.SetId(2);
            selector5.AddChild(_node53);
            selector5.SetHasEvents(selector5.HasEvents() | _node53.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node4 _node54 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node4();
            _node54.SetClassNameString("Condition");
            _node54.SetId(4);
            selector5.AddChild(_node54);
            selector5.SetHasEvents(selector5.HasEvents() | _node54.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node10 _node55 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node10();
            _node55.SetClassNameString("Condition");
            _node55.SetId(10);
            selector5.AddChild(_node55);
            selector5.SetHasEvents(selector5.HasEvents() | _node55.HasEvents());
            sequence14.SetHasEvents(sequence14.HasEvents() | selector5.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node119 _node56 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node119();
            _node56.SetClassNameString("Condition");
            _node56.SetId(0x77);
            sequence14.AddChild(_node56);
            sequence14.SetHasEvents(sequence14.HasEvents() | _node56.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node120 _node57 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node120();
            _node57.SetClassNameString("Action");
            _node57.SetId(120);
            sequence14.AddChild(_node57);
            sequence14.SetHasEvents(sequence14.HasEvents() | _node57.HasEvents());
            selector4.SetHasEvents(selector4.HasEvents() | sequence14.HasEvents());
            Sequence sequence15 = new Sequence();
            sequence15.SetClassNameString("Sequence");
            sequence15.SetId(0x16);
            selector4.AddChild(sequence15);
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node23 _node58 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node23();
            _node58.SetClassNameString("Condition");
            _node58.SetId(0x17);
            sequence15.AddChild(_node58);
            sequence15.SetHasEvents(sequence15.HasEvents() | _node58.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterPassive_node121 _node59 = new Assignment_bt_WrapperAI_Monster_BTMonsterPassive_node121();
            _node59.SetClassNameString("Assignment");
            _node59.SetId(0x79);
            sequence15.AddChild(_node59);
            sequence15.SetHasEvents(sequence15.HasEvents() | _node59.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node26 _node60 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node26();
            _node60.SetClassNameString("Condition");
            _node60.SetId(0x1a);
            sequence15.AddChild(_node60);
            sequence15.SetHasEvents(sequence15.HasEvents() | _node60.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node122 _node61 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node122();
            _node61.SetClassNameString("Action");
            _node61.SetId(0x7a);
            sequence15.AddChild(_node61);
            sequence15.SetHasEvents(sequence15.HasEvents() | _node61.HasEvents());
            selector4.SetHasEvents(selector4.HasEvents() | sequence15.HasEvents());
            Sequence sequence16 = new Sequence();
            sequence16.SetClassNameString("Sequence");
            sequence16.SetId(0x7b);
            selector4.AddChild(sequence16);
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node37 _node62 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node37();
            _node62.SetClassNameString("Condition");
            _node62.SetId(0x25);
            sequence16.AddChild(_node62);
            sequence16.SetHasEvents(sequence16.HasEvents() | _node62.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node38 _node63 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node38();
            _node63.SetClassNameString("Condition");
            _node63.SetId(0x26);
            sequence16.AddChild(_node63);
            sequence16.SetHasEvents(sequence16.HasEvents() | _node63.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node124 _node64 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node124();
            _node64.SetClassNameString("Action");
            _node64.SetId(0x7c);
            sequence16.AddChild(_node64);
            sequence16.SetHasEvents(sequence16.HasEvents() | _node64.HasEvents());
            selector4.SetHasEvents(selector4.HasEvents() | sequence16.HasEvents());
            sequence13.SetHasEvents(sequence13.HasEvents() | selector4.HasEvents());
            selector3.SetHasEvents(selector3.HasEvents() | sequence13.HasEvents());
            Sequence sequence17 = new Sequence();
            sequence17.SetClassNameString("Sequence");
            sequence17.SetId(0x97);
            selector3.AddChild(sequence17);
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node25 _node65 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node25();
            _node65.SetClassNameString("Condition");
            _node65.SetId(0x19);
            sequence17.AddChild(_node65);
            sequence17.SetHasEvents(sequence17.HasEvents() | _node65.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterPassive_node155 _node66 = new Assignment_bt_WrapperAI_Monster_BTMonsterPassive_node155();
            _node66.SetClassNameString("Assignment");
            _node66.SetId(0x9b);
            sequence17.AddChild(_node66);
            sequence17.SetHasEvents(sequence17.HasEvents() | _node66.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterPassive_node182 _node67 = new Assignment_bt_WrapperAI_Monster_BTMonsterPassive_node182();
            _node67.SetClassNameString("Assignment");
            _node67.SetId(0xb6);
            sequence17.AddChild(_node67);
            sequence17.SetHasEvents(sequence17.HasEvents() | _node67.HasEvents());
            Selector selector6 = new Selector();
            selector6.SetClassNameString("Selector");
            selector6.SetId(0x27);
            sequence17.AddChild(selector6);
            Sequence sequence18 = new Sequence();
            sequence18.SetClassNameString("Sequence");
            sequence18.SetId(0x7d);
            selector6.AddChild(sequence18);
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node126 _node68 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node126();
            _node68.SetClassNameString("Action");
            _node68.SetId(0x7e);
            sequence18.AddChild(_node68);
            sequence18.SetHasEvents(sequence18.HasEvents() | _node68.HasEvents());
            Selector selector7 = new Selector();
            selector7.SetClassNameString("Selector");
            selector7.SetId(0x7f);
            sequence18.AddChild(selector7);
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node128 _node69 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node128();
            _node69.SetClassNameString("Condition");
            _node69.SetId(0x80);
            selector7.AddChild(_node69);
            selector7.SetHasEvents(selector7.HasEvents() | _node69.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node132 _node70 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node132();
            _node70.SetClassNameString("Condition");
            _node70.SetId(0x84);
            selector7.AddChild(_node70);
            selector7.SetHasEvents(selector7.HasEvents() | _node70.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node135 _node71 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node135();
            _node71.SetClassNameString("Condition");
            _node71.SetId(0x87);
            selector7.AddChild(_node71);
            selector7.SetHasEvents(selector7.HasEvents() | _node71.HasEvents());
            sequence18.SetHasEvents(sequence18.HasEvents() | selector7.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node49 _node72 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node49();
            _node72.SetClassNameString("Condition");
            _node72.SetId(0x31);
            sequence18.AddChild(_node72);
            sequence18.SetHasEvents(sequence18.HasEvents() | _node72.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node136 _node73 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node136();
            _node73.SetClassNameString("Action");
            _node73.SetId(0x88);
            sequence18.AddChild(_node73);
            sequence18.SetHasEvents(sequence18.HasEvents() | _node73.HasEvents());
            selector6.SetHasEvents(selector6.HasEvents() | sequence18.HasEvents());
            Sequence sequence19 = new Sequence();
            sequence19.SetClassNameString("Sequence");
            sequence19.SetId(0x33);
            selector6.AddChild(sequence19);
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node52 _node74 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node52();
            _node74.SetClassNameString("Condition");
            _node74.SetId(0x34);
            sequence19.AddChild(_node74);
            sequence19.SetHasEvents(sequence19.HasEvents() | _node74.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterPassive_node53 _node75 = new Assignment_bt_WrapperAI_Monster_BTMonsterPassive_node53();
            _node75.SetClassNameString("Assignment");
            _node75.SetId(0x35);
            sequence19.AddChild(_node75);
            sequence19.SetHasEvents(sequence19.HasEvents() | _node75.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node54 _node76 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node54();
            _node76.SetClassNameString("Condition");
            _node76.SetId(0x36);
            sequence19.AddChild(_node76);
            sequence19.SetHasEvents(sequence19.HasEvents() | _node76.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node55 _node77 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node55();
            _node77.SetClassNameString("Action");
            _node77.SetId(0x37);
            sequence19.AddChild(_node77);
            sequence19.SetHasEvents(sequence19.HasEvents() | _node77.HasEvents());
            selector6.SetHasEvents(selector6.HasEvents() | sequence19.HasEvents());
            Sequence sequence20 = new Sequence();
            sequence20.SetClassNameString("Sequence");
            sequence20.SetId(0x38);
            selector6.AddChild(sequence20);
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node140 _node78 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node140();
            _node78.SetClassNameString("Condition");
            _node78.SetId(140);
            sequence20.AddChild(_node78);
            sequence20.SetHasEvents(sequence20.HasEvents() | _node78.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node141 _node79 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node141();
            _node79.SetClassNameString("Condition");
            _node79.SetId(0x8d);
            sequence20.AddChild(_node79);
            sequence20.SetHasEvents(sequence20.HasEvents() | _node79.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node149 _node80 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node149();
            _node80.SetClassNameString("Action");
            _node80.SetId(0x95);
            sequence20.AddChild(_node80);
            sequence20.SetHasEvents(sequence20.HasEvents() | _node80.HasEvents());
            selector6.SetHasEvents(selector6.HasEvents() | sequence20.HasEvents());
            sequence17.SetHasEvents(sequence17.HasEvents() | selector6.HasEvents());
            selector3.SetHasEvents(selector3.HasEvents() | sequence17.HasEvents());
            Sequence sequence21 = new Sequence();
            sequence21.SetClassNameString("Sequence");
            sequence21.SetId(0xb7);
            selector3.AddChild(sequence21);
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node30 _node81 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node30();
            _node81.SetClassNameString("Condition");
            _node81.SetId(30);
            sequence21.AddChild(_node81);
            sequence21.SetHasEvents(sequence21.HasEvents() | _node81.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterPassive_node184 _node82 = new Assignment_bt_WrapperAI_Monster_BTMonsterPassive_node184();
            _node82.SetClassNameString("Assignment");
            _node82.SetId(0xb8);
            sequence21.AddChild(_node82);
            sequence21.SetHasEvents(sequence21.HasEvents() | _node82.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterPassive_node193 _node83 = new Assignment_bt_WrapperAI_Monster_BTMonsterPassive_node193();
            _node83.SetClassNameString("Assignment");
            _node83.SetId(0xc1);
            sequence21.AddChild(_node83);
            sequence21.SetHasEvents(sequence21.HasEvents() | _node83.HasEvents());
            Selector selector8 = new Selector();
            selector8.SetClassNameString("Selector");
            selector8.SetId(0x2c);
            sequence21.AddChild(selector8);
            Sequence sequence22 = new Sequence();
            sequence22.SetClassNameString("Sequence");
            sequence22.SetId(150);
            selector8.AddChild(sequence22);
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node152 _node84 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node152();
            _node84.SetClassNameString("Action");
            _node84.SetId(0x98);
            sequence22.AddChild(_node84);
            sequence22.SetHasEvents(sequence22.HasEvents() | _node84.HasEvents());
            Selector selector9 = new Selector();
            selector9.SetClassNameString("Selector");
            selector9.SetId(0x40);
            sequence22.AddChild(selector9);
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node65 _node85 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node65();
            _node85.SetClassNameString("Condition");
            _node85.SetId(0x41);
            selector9.AddChild(_node85);
            selector9.SetHasEvents(selector9.HasEvents() | _node85.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node73 _node86 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node73();
            _node86.SetClassNameString("Condition");
            _node86.SetId(0x49);
            selector9.AddChild(_node86);
            selector9.SetHasEvents(selector9.HasEvents() | _node86.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node74 _node87 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node74();
            _node87.SetClassNameString("Condition");
            _node87.SetId(0x4a);
            selector9.AddChild(_node87);
            selector9.SetHasEvents(selector9.HasEvents() | _node87.HasEvents());
            sequence22.SetHasEvents(sequence22.HasEvents() | selector9.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node76 _node88 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node76();
            _node88.SetClassNameString("Condition");
            _node88.SetId(0x4c);
            sequence22.AddChild(_node88);
            sequence22.SetHasEvents(sequence22.HasEvents() | _node88.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node78 _node89 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node78();
            _node89.SetClassNameString("Action");
            _node89.SetId(0x4e);
            sequence22.AddChild(_node89);
            sequence22.SetHasEvents(sequence22.HasEvents() | _node89.HasEvents());
            selector8.SetHasEvents(selector8.HasEvents() | sequence22.HasEvents());
            Sequence sequence23 = new Sequence();
            sequence23.SetClassNameString("Sequence");
            sequence23.SetId(0x4f);
            selector8.AddChild(sequence23);
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node80 _node90 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node80();
            _node90.SetClassNameString("Condition");
            _node90.SetId(80);
            sequence23.AddChild(_node90);
            sequence23.SetHasEvents(sequence23.HasEvents() | _node90.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterPassive_node81 _node91 = new Assignment_bt_WrapperAI_Monster_BTMonsterPassive_node81();
            _node91.SetClassNameString("Assignment");
            _node91.SetId(0x51);
            sequence23.AddChild(_node91);
            sequence23.SetHasEvents(sequence23.HasEvents() | _node91.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node82 _node92 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node82();
            _node92.SetClassNameString("Condition");
            _node92.SetId(0x52);
            sequence23.AddChild(_node92);
            sequence23.SetHasEvents(sequence23.HasEvents() | _node92.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node83 _node93 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node83();
            _node93.SetClassNameString("Action");
            _node93.SetId(0x53);
            sequence23.AddChild(_node93);
            sequence23.SetHasEvents(sequence23.HasEvents() | _node93.HasEvents());
            selector8.SetHasEvents(selector8.HasEvents() | sequence23.HasEvents());
            Sequence sequence24 = new Sequence();
            sequence24.SetClassNameString("Sequence");
            sequence24.SetId(0x54);
            selector8.AddChild(sequence24);
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node153 _node94 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node153();
            _node94.SetClassNameString("Condition");
            _node94.SetId(0x99);
            sequence24.AddChild(_node94);
            sequence24.SetHasEvents(sequence24.HasEvents() | _node94.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node154 _node95 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node154();
            _node95.SetClassNameString("Condition");
            _node95.SetId(0x9a);
            sequence24.AddChild(_node95);
            sequence24.SetHasEvents(sequence24.HasEvents() | _node95.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node157 _node96 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node157();
            _node96.SetClassNameString("Action");
            _node96.SetId(0x9d);
            sequence24.AddChild(_node96);
            sequence24.SetHasEvents(sequence24.HasEvents() | _node96.HasEvents());
            selector8.SetHasEvents(selector8.HasEvents() | sequence24.HasEvents());
            sequence21.SetHasEvents(sequence21.HasEvents() | selector8.HasEvents());
            selector3.SetHasEvents(selector3.HasEvents() | sequence21.HasEvents());
            Sequence sequence25 = new Sequence();
            sequence25.SetClassNameString("Sequence");
            sequence25.SetId(0xc2);
            selector3.AddChild(sequence25);
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node50 _node97 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node50();
            _node97.SetClassNameString("Condition");
            _node97.SetId(50);
            sequence25.AddChild(_node97);
            sequence25.SetHasEvents(sequence25.HasEvents() | _node97.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterPassive_node195 _node98 = new Assignment_bt_WrapperAI_Monster_BTMonsterPassive_node195();
            _node98.SetClassNameString("Assignment");
            _node98.SetId(0xc3);
            sequence25.AddChild(_node98);
            sequence25.SetHasEvents(sequence25.HasEvents() | _node98.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterPassive_node200 _node99 = new Assignment_bt_WrapperAI_Monster_BTMonsterPassive_node200();
            _node99.SetClassNameString("Assignment");
            _node99.SetId(200);
            sequence25.AddChild(_node99);
            sequence25.SetHasEvents(sequence25.HasEvents() | _node99.HasEvents());
            Selector selector10 = new Selector();
            selector10.SetClassNameString("Selector");
            selector10.SetId(0x2d);
            sequence25.AddChild(selector10);
            Sequence sequence26 = new Sequence();
            sequence26.SetClassNameString("Sequence");
            sequence26.SetId(0x9e);
            selector10.AddChild(sequence26);
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node89 _node100 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node89();
            _node100.SetClassNameString("Action");
            _node100.SetId(0x59);
            sequence26.AddChild(_node100);
            sequence26.SetHasEvents(sequence26.HasEvents() | _node100.HasEvents());
            Selector selector11 = new Selector();
            selector11.SetClassNameString("Selector");
            selector11.SetId(90);
            sequence26.AddChild(selector11);
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node91 _node101 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node91();
            _node101.SetClassNameString("Condition");
            _node101.SetId(0x5b);
            selector11.AddChild(_node101);
            selector11.SetHasEvents(selector11.HasEvents() | _node101.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node92 _node102 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node92();
            _node102.SetClassNameString("Condition");
            _node102.SetId(0x5c);
            selector11.AddChild(_node102);
            selector11.SetHasEvents(selector11.HasEvents() | _node102.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node93 _node103 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node93();
            _node103.SetClassNameString("Condition");
            _node103.SetId(0x5d);
            selector11.AddChild(_node103);
            selector11.SetHasEvents(selector11.HasEvents() | _node103.HasEvents());
            sequence26.SetHasEvents(sequence26.HasEvents() | selector11.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node94 _node104 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node94();
            _node104.SetClassNameString("Condition");
            _node104.SetId(0x5e);
            sequence26.AddChild(_node104);
            sequence26.SetHasEvents(sequence26.HasEvents() | _node104.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node95 _node105 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node95();
            _node105.SetClassNameString("Action");
            _node105.SetId(0x5f);
            sequence26.AddChild(_node105);
            sequence26.SetHasEvents(sequence26.HasEvents() | _node105.HasEvents());
            selector10.SetHasEvents(selector10.HasEvents() | sequence26.HasEvents());
            Sequence sequence27 = new Sequence();
            sequence27.SetClassNameString("Sequence");
            sequence27.SetId(0x60);
            selector10.AddChild(sequence27);
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node97 _node106 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node97();
            _node106.SetClassNameString("Condition");
            _node106.SetId(0x61);
            sequence27.AddChild(_node106);
            sequence27.SetHasEvents(sequence27.HasEvents() | _node106.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterPassive_node99 _node107 = new Assignment_bt_WrapperAI_Monster_BTMonsterPassive_node99();
            _node107.SetClassNameString("Assignment");
            _node107.SetId(0x63);
            sequence27.AddChild(_node107);
            sequence27.SetHasEvents(sequence27.HasEvents() | _node107.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node101 _node108 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node101();
            _node108.SetClassNameString("Condition");
            _node108.SetId(0x65);
            sequence27.AddChild(_node108);
            sequence27.SetHasEvents(sequence27.HasEvents() | _node108.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node102 _node109 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node102();
            _node109.SetClassNameString("Action");
            _node109.SetId(0x66);
            sequence27.AddChild(_node109);
            sequence27.SetHasEvents(sequence27.HasEvents() | _node109.HasEvents());
            selector10.SetHasEvents(selector10.HasEvents() | sequence27.HasEvents());
            Sequence sequence28 = new Sequence();
            sequence28.SetClassNameString("Sequence");
            sequence28.SetId(0x67);
            selector10.AddChild(sequence28);
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node104 _node110 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node104();
            _node110.SetClassNameString("Condition");
            _node110.SetId(0x68);
            sequence28.AddChild(_node110);
            sequence28.SetHasEvents(sequence28.HasEvents() | _node110.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node105 _node111 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node105();
            _node111.SetClassNameString("Condition");
            _node111.SetId(0x69);
            sequence28.AddChild(_node111);
            sequence28.SetHasEvents(sequence28.HasEvents() | _node111.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node106 _node112 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node106();
            _node112.SetClassNameString("Action");
            _node112.SetId(0x6a);
            sequence28.AddChild(_node112);
            sequence28.SetHasEvents(sequence28.HasEvents() | _node112.HasEvents());
            selector10.SetHasEvents(selector10.HasEvents() | sequence28.HasEvents());
            sequence25.SetHasEvents(sequence25.HasEvents() | selector10.HasEvents());
            selector3.SetHasEvents(selector3.HasEvents() | sequence25.HasEvents());
            IfElse else7 = new IfElse();
            else7.SetClassNameString("IfElse");
            else7.SetId(0x3a);
            selector3.AddChild(else7);
            Sequence sequence29 = new Sequence();
            sequence29.SetClassNameString("Sequence");
            sequence29.SetId(0x3e);
            else7.AddChild(sequence29);
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node57 _node113 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node57();
            _node113.SetClassNameString("Condition");
            _node113.SetId(0x39);
            sequence29.AddChild(_node113);
            sequence29.SetHasEvents(sequence29.HasEvents() | _node113.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node9 _node114 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node9();
            _node114.SetClassNameString("Action");
            _node114.SetId(9);
            sequence29.AddChild(_node114);
            sequence29.SetHasEvents(sequence29.HasEvents() | _node114.HasEvents());
            else7.SetHasEvents(else7.HasEvents() | sequence29.HasEvents());
            Sequence sequence30 = new Sequence();
            sequence30.SetClassNameString("Sequence");
            sequence30.SetId(0x3b);
            else7.AddChild(sequence30);
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node444 _node115 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node444();
            _node115.SetClassNameString("Action");
            _node115.SetId(0x1bc);
            sequence30.AddChild(_node115);
            sequence30.SetHasEvents(sequence30.HasEvents() | _node115.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node201 _node116 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node201();
            _node116.SetClassNameString("Action");
            _node116.SetId(0xc9);
            sequence30.AddChild(_node116);
            sequence30.SetHasEvents(sequence30.HasEvents() | _node116.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node241 _node117 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node241();
            _node117.SetClassNameString("Action");
            _node117.SetId(0xf1);
            sequence30.AddChild(_node117);
            sequence30.SetHasEvents(sequence30.HasEvents() | _node117.HasEvents());
            else7.SetHasEvents(else7.HasEvents() | sequence30.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node12 _node118 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node12();
            _node118.SetClassNameString("Action");
            _node118.SetId(12);
            else7.AddChild(_node118);
            else7.SetHasEvents(else7.HasEvents() | _node118.HasEvents());
            selector3.SetHasEvents(selector3.HasEvents() | else7.HasEvents());
            sequence12.SetHasEvents(sequence12.HasEvents() | selector3.HasEvents());
            Sequence sequence31 = new Sequence();
            sequence31.SetClassNameString("Sequence");
            sequence31.SetId(0xca);
            sequence12.AddChild(sequence31);
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node129 _node119 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node129();
            _node119.SetClassNameString("Action");
            _node119.SetId(0x81);
            sequence31.AddChild(_node119);
            sequence31.SetHasEvents(sequence31.HasEvents() | _node119.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node85 _node120 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node85();
            _node120.SetClassNameString("Action");
            _node120.SetId(0x55);
            sequence31.AddChild(_node120);
            sequence31.SetHasEvents(sequence31.HasEvents() | _node120.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node86 _node121 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node86();
            _node121.SetClassNameString("Action");
            _node121.SetId(0x56);
            sequence31.AddChild(_node121);
            sequence31.SetHasEvents(sequence31.HasEvents() | _node121.HasEvents());
            DecoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterPassive_node87 _node122 = new DecoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterPassive_node87();
            _node122.SetClassNameString("DecoratorLoopUntil");
            _node122.SetId(0x57);
            sequence31.AddChild(_node122);
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node88 _node123 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node88();
            _node123.SetClassNameString("Condition");
            _node123.SetId(0x58);
            _node122.AddChild(_node123);
            _node122.SetHasEvents(_node122.HasEvents() | _node123.HasEvents());
            sequence31.SetHasEvents(sequence31.HasEvents() | _node122.HasEvents());
            sequence12.SetHasEvents(sequence12.HasEvents() | sequence31.HasEvents());
            else6.SetHasEvents(else6.HasEvents() | sequence12.HasEvents());
            Sequence sequence32 = new Sequence();
            sequence32.SetClassNameString("Sequence");
            sequence32.SetId(0xd0);
            else6.AddChild(sequence32);
            Assignment_bt_WrapperAI_Monster_BTMonsterPassive_node229 _node124 = new Assignment_bt_WrapperAI_Monster_BTMonsterPassive_node229();
            _node124.SetClassNameString("Assignment");
            _node124.SetId(0xe5);
            sequence32.AddChild(_node124);
            sequence32.SetHasEvents(sequence32.HasEvents() | _node124.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node175 _node125 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node175();
            _node125.SetClassNameString("Condition");
            _node125.SetId(0xaf);
            sequence32.AddChild(_node125);
            sequence32.SetHasEvents(sequence32.HasEvents() | _node125.HasEvents());
            else6.SetHasEvents(else6.HasEvents() | sequence32.HasEvents());
            sequence9.SetHasEvents(sequence9.HasEvents() | else6.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node63 _node126 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node63();
            _node126.SetClassNameString("Action");
            _node126.SetId(0x3f);
            sequence9.AddChild(_node126);
            sequence9.SetHasEvents(sequence9.HasEvents() | _node126.HasEvents());
            WaitFrames_bt_WrapperAI_Monster_BTMonsterPassive_node17 _node127 = new WaitFrames_bt_WrapperAI_Monster_BTMonsterPassive_node17();
            _node127.SetClassNameString("WaitFrames");
            _node127.SetId(0x11);
            sequence9.AddChild(_node127);
            sequence9.SetHasEvents(sequence9.HasEvents() | _node127.HasEvents());
            selector2.SetHasEvents(selector2.HasEvents() | sequence9.HasEvents());
            precondition2.SetHasEvents(precondition2.HasEvents() | selector2.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition2.HasEvents());
            WithPrecondition precondition3 = new WithPrecondition();
            precondition3.SetClassNameString("WithPrecondition");
            precondition3.SetId(0x203);
            loop.AddChild(precondition3);
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node516 _node128 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node516();
            _node128.SetClassNameString("Condition");
            _node128.SetId(0x204);
            precondition3.AddChild(_node128);
            precondition3.SetHasEvents(precondition3.HasEvents() | _node128.HasEvents());
            Selector selector12 = new Selector();
            selector12.SetClassNameString("Selector");
            selector12.SetId(0x6b);
            precondition3.AddChild(selector12);
            Sequence sequence33 = new Sequence();
            sequence33.SetClassNameString("Sequence");
            sequence33.SetId(0x6c);
            selector12.AddChild(sequence33);
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node109 _node129 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node109();
            _node129.SetClassNameString("Condition");
            _node129.SetId(0x6d);
            sequence33.AddChild(_node129);
            sequence33.SetHasEvents(sequence33.HasEvents() | _node129.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterPassive_node110 _node130 = new Assignment_bt_WrapperAI_Monster_BTMonsterPassive_node110();
            _node130.SetClassNameString("Assignment");
            _node130.SetId(110);
            sequence33.AddChild(_node130);
            sequence33.SetHasEvents(sequence33.HasEvents() | _node130.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node112 _node131 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node112();
            _node131.SetClassNameString("Action");
            _node131.SetId(0x70);
            sequence33.AddChild(_node131);
            sequence33.SetHasEvents(sequence33.HasEvents() | _node131.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node113 _node132 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node113();
            _node132.SetClassNameString("Action");
            _node132.SetId(0x71);
            sequence33.AddChild(_node132);
            sequence33.SetHasEvents(sequence33.HasEvents() | _node132.HasEvents());
            selector12.SetHasEvents(selector12.HasEvents() | sequence33.HasEvents());
            Sequence sequence34 = new Sequence();
            sequence34.SetClassNameString("Sequence");
            sequence34.SetId(0x205);
            selector12.AddChild(sequence34);
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node114 _node133 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node114();
            _node133.SetClassNameString("Condition");
            _node133.SetId(0x72);
            sequence34.AddChild(_node133);
            sequence34.SetHasEvents(sequence34.HasEvents() | _node133.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node518 _node134 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node518();
            _node134.SetClassNameString("Action");
            _node134.SetId(0x206);
            sequence34.AddChild(_node134);
            sequence34.SetHasEvents(sequence34.HasEvents() | _node134.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node519 _node135 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node519();
            _node135.SetClassNameString("Action");
            _node135.SetId(0x207);
            sequence34.AddChild(_node135);
            sequence34.SetHasEvents(sequence34.HasEvents() | _node135.HasEvents());
            IfElse else8 = new IfElse();
            else8.SetClassNameString("IfElse");
            else8.SetId(520);
            sequence34.AddChild(else8);
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node521 _node136 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node521();
            _node136.SetClassNameString("Condition");
            _node136.SetId(0x209);
            else8.AddChild(_node136);
            else8.SetHasEvents(else8.HasEvents() | _node136.HasEvents());
            Sequence sequence35 = new Sequence();
            sequence35.SetClassNameString("Sequence");
            sequence35.SetId(0x20a);
            else8.AddChild(sequence35);
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node523 _node137 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node523();
            _node137.SetClassNameString("Action");
            _node137.SetId(0x20b);
            sequence35.AddChild(_node137);
            sequence35.SetHasEvents(sequence35.HasEvents() | _node137.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node524 _node138 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node524();
            _node138.SetClassNameString("Action");
            _node138.SetId(0x20c);
            sequence35.AddChild(_node138);
            sequence35.SetHasEvents(sequence35.HasEvents() | _node138.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node526 _node139 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node526();
            _node139.SetClassNameString("Action");
            _node139.SetId(0x20e);
            sequence35.AddChild(_node139);
            sequence35.SetHasEvents(sequence35.HasEvents() | _node139.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node115 _node140 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node115();
            _node140.SetClassNameString("Action");
            _node140.SetId(0x73);
            sequence35.AddChild(_node140);
            sequence35.SetHasEvents(sequence35.HasEvents() | _node140.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node530 _node141 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node530();
            _node141.SetClassNameString("Action");
            _node141.SetId(530);
            sequence35.AddChild(_node141);
            sequence35.SetHasEvents(sequence35.HasEvents() | _node141.HasEvents());
            DecoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterPassive_node531 _node142 = new DecoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterPassive_node531();
            _node142.SetClassNameString("DecoratorLoopUntil");
            _node142.SetId(0x213);
            sequence35.AddChild(_node142);
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node532 _node143 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node532();
            _node143.SetClassNameString("Condition");
            _node143.SetId(0x214);
            _node142.AddChild(_node143);
            _node142.SetHasEvents(_node142.HasEvents() | _node143.HasEvents());
            sequence35.SetHasEvents(sequence35.HasEvents() | _node142.HasEvents());
            else8.SetHasEvents(else8.HasEvents() | sequence35.HasEvents());
            Sequence sequence36 = new Sequence();
            sequence36.SetClassNameString("Sequence");
            sequence36.SetId(0x215);
            else8.AddChild(sequence36);
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node116 _node144 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node116();
            _node144.SetClassNameString("Action");
            _node144.SetId(0x74);
            sequence36.AddChild(_node144);
            sequence36.SetHasEvents(sequence36.HasEvents() | _node144.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node535 _node145 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node535();
            _node145.SetClassNameString("Action");
            _node145.SetId(0x217);
            sequence36.AddChild(_node145);
            sequence36.SetHasEvents(sequence36.HasEvents() | _node145.HasEvents());
            DecoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterPassive_node536 _node146 = new DecoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterPassive_node536();
            _node146.SetClassNameString("DecoratorLoopUntil");
            _node146.SetId(0x218);
            sequence36.AddChild(_node146);
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node537 _node147 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node537();
            _node147.SetClassNameString("Condition");
            _node147.SetId(0x219);
            _node146.AddChild(_node147);
            _node146.SetHasEvents(_node146.HasEvents() | _node147.HasEvents());
            sequence36.SetHasEvents(sequence36.HasEvents() | _node146.HasEvents());
            else8.SetHasEvents(else8.HasEvents() | sequence36.HasEvents());
            sequence34.SetHasEvents(sequence34.HasEvents() | else8.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node538 _node148 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node538();
            _node148.SetClassNameString("Action");
            _node148.SetId(0x21a);
            sequence34.AddChild(_node148);
            sequence34.SetHasEvents(sequence34.HasEvents() | _node148.HasEvents());
            selector12.SetHasEvents(selector12.HasEvents() | sequence34.HasEvents());
            precondition3.SetHasEvents(precondition3.HasEvents() | selector12.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition3.HasEvents());
            WithPrecondition precondition4 = new WithPrecondition();
            precondition4.SetClassNameString("WithPrecondition");
            precondition4.SetId(0x8e);
            loop.AddChild(precondition4);
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node143 _node149 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node143();
            _node149.SetClassNameString("Condition");
            _node149.SetId(0x8f);
            precondition4.AddChild(_node149);
            precondition4.SetHasEvents(precondition4.HasEvents() | _node149.HasEvents());
            Sequence sequence37 = new Sequence();
            sequence37.SetClassNameString("Sequence");
            sequence37.SetId(0x90);
            precondition4.AddChild(sequence37);
            Selector selector13 = new Selector();
            selector13.SetClassNameString("Selector");
            selector13.SetId(0x1e7);
            sequence37.AddChild(selector13);
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node488 _node150 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node488();
            _node150.SetClassNameString("Action");
            _node150.SetId(0x1e8);
            selector13.AddChild(_node150);
            selector13.SetHasEvents(selector13.HasEvents() | _node150.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node145 _node151 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node145();
            _node151.SetClassNameString("Action");
            _node151.SetId(0x91);
            selector13.AddChild(_node151);
            selector13.SetHasEvents(selector13.HasEvents() | _node151.HasEvents());
            sequence37.SetHasEvents(sequence37.HasEvents() | selector13.HasEvents());
            DecoratorLoop_bt_WrapperAI_Monster_BTMonsterPassive_node146 _node152 = new DecoratorLoop_bt_WrapperAI_Monster_BTMonsterPassive_node146();
            _node152.SetClassNameString("DecoratorLoop");
            _node152.SetId(0x92);
            sequence37.AddChild(_node152);
            Noop noop3 = new Noop();
            noop3.SetClassNameString("Noop");
            noop3.SetId(0x93);
            _node152.AddChild(noop3);
            _node152.SetHasEvents(_node152.HasEvents() | noop3.HasEvents());
            sequence37.SetHasEvents(sequence37.HasEvents() | _node152.HasEvents());
            precondition4.SetHasEvents(precondition4.HasEvents() | sequence37.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition4.HasEvents());
            WithPrecondition precondition5 = new WithPrecondition();
            precondition5.SetClassNameString("WithPrecondition");
            precondition5.SetId(0x22);
            loop.AddChild(precondition5);
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node40 _node153 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node40();
            _node153.SetClassNameString("Condition");
            _node153.SetId(40);
            precondition5.AddChild(_node153);
            precondition5.SetHasEvents(precondition5.HasEvents() | _node153.HasEvents());
            Sequence sequence38 = new Sequence();
            sequence38.SetClassNameString("Sequence");
            sequence38.SetId(0x29);
            precondition5.AddChild(sequence38);
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node42 _node154 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node42();
            _node154.SetClassNameString("Action");
            _node154.SetId(0x2a);
            sequence38.AddChild(_node154);
            sequence38.SetHasEvents(sequence38.HasEvents() | _node154.HasEvents());
            DecoratorLoop_bt_WrapperAI_Monster_BTMonsterPassive_node43 _node155 = new DecoratorLoop_bt_WrapperAI_Monster_BTMonsterPassive_node43();
            _node155.SetClassNameString("DecoratorLoop");
            _node155.SetId(0x2b);
            sequence38.AddChild(_node155);
            Noop noop4 = new Noop();
            noop4.SetClassNameString("Noop");
            noop4.SetId(0x1ca);
            _node155.AddChild(noop4);
            _node155.SetHasEvents(_node155.HasEvents() | noop4.HasEvents());
            sequence38.SetHasEvents(sequence38.HasEvents() | _node155.HasEvents());
            precondition5.SetHasEvents(precondition5.HasEvents() | sequence38.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition5.HasEvents());
            WithPrecondition precondition6 = new WithPrecondition();
            precondition6.SetClassNameString("WithPrecondition");
            precondition6.SetId(450);
            loop.AddChild(precondition6);
            Condition_bt_WrapperAI_Monster_BTMonsterPassive_node454 _node156 = new Condition_bt_WrapperAI_Monster_BTMonsterPassive_node454();
            _node156.SetClassNameString("Condition");
            _node156.SetId(0x1c6);
            precondition6.AddChild(_node156);
            precondition6.SetHasEvents(precondition6.HasEvents() | _node156.HasEvents());
            Sequence sequence39 = new Sequence();
            sequence39.SetClassNameString("Sequence");
            sequence39.SetId(0x1c7);
            precondition6.AddChild(sequence39);
            Action_bt_WrapperAI_Monster_BTMonsterPassive_node456 _node157 = new Action_bt_WrapperAI_Monster_BTMonsterPassive_node456();
            _node157.SetClassNameString("Action");
            _node157.SetId(0x1c8);
            sequence39.AddChild(_node157);
            sequence39.SetHasEvents(sequence39.HasEvents() | _node157.HasEvents());
            DecoratorLoop_bt_WrapperAI_Monster_BTMonsterPassive_node457 _node158 = new DecoratorLoop_bt_WrapperAI_Monster_BTMonsterPassive_node457();
            _node158.SetClassNameString("DecoratorLoop");
            _node158.SetId(0x1c9);
            sequence39.AddChild(_node158);
            Noop noop5 = new Noop();
            noop5.SetClassNameString("Noop");
            noop5.SetId(0x75);
            _node158.AddChild(noop5);
            _node158.SetHasEvents(_node158.HasEvents() | noop5.HasEvents());
            sequence39.SetHasEvents(sequence39.HasEvents() | _node158.HasEvents());
            precondition6.SetHasEvents(precondition6.HasEvents() | sequence39.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition6.HasEvents());
            _node6.SetHasEvents(_node6.HasEvents() | loop.HasEvents());
            pChild.SetHasEvents(pChild.HasEvents() | _node6.HasEvents());
            bt.SetHasEvents(bt.HasEvents() | pChild.HasEvents());
            return true;
        }
    }
}

