namespace behaviac
{
    using System;

    public static class bt_WrapperAI_Organ_CrystalWithAttack
    {
        public static bool build_behavior_tree(BehaviorTree bt)
        {
            bt.SetClassNameString("BehaviorTree");
            bt.SetId(-1);
            bt.SetName("WrapperAI/Organ/CrystalWithAttack");
            bt.AddPar("uint", "p_targetID", "0", string.Empty);
            bt.AddPar("int", "p_srchRange", "0", string.Empty);
            bt.AddPar("uint", "p_CmdID", "0", string.Empty);
            bt.AddPar("uint", "p_commandTarget", "0", string.Empty);
            bt.AddPar("int", "p_waitFrame", "0", string.Empty);
            bt.AddPar("CSProtocol.COM_PLAYERCAMP", "p_camp", "COM_PLAYERCAMP_1", string.Empty);
            bt.AddPar("int", "p_pathIndex", "0", string.Empty);
            bt.AddPar("int", "p_attackTowerWaitFrame", "0", string.Empty);
            bt.AddPar("uint", "p_nearCommanTarget", "0", string.Empty);
            Sequence pChild = new Sequence();
            pChild.SetClassNameString("Sequence");
            pChild.SetId(0);
            bt.AddChild(pChild);
            Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node82 _node = new Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node82();
            _node.SetClassNameString("Assignment");
            _node.SetId(0x52);
            pChild.AddChild(_node);
            pChild.SetHasEvents(pChild.HasEvents() | _node.HasEvents());
            DecoratorLoop_bt_WrapperAI_Organ_CrystalWithAttack_node27 _node2 = new DecoratorLoop_bt_WrapperAI_Organ_CrystalWithAttack_node27();
            _node2.SetClassNameString("DecoratorLoop");
            _node2.SetId(0x1b);
            pChild.AddChild(_node2);
            Parallel_bt_WrapperAI_Organ_CrystalWithAttack_node14 _node3 = new Parallel_bt_WrapperAI_Organ_CrystalWithAttack_node14();
            _node3.SetClassNameString("Parallel");
            _node3.SetId(14);
            _node2.AddChild(_node3);
            SelectorLoop loop = new SelectorLoop();
            loop.SetClassNameString("SelectorLoop");
            loop.SetId(1);
            _node3.AddChild(loop);
            WithPrecondition precondition = new WithPrecondition();
            precondition.SetClassNameString("WithPrecondition");
            precondition.SetId(0x1a);
            loop.AddChild(precondition);
            Sequence sequence2 = new Sequence();
            sequence2.SetClassNameString("Sequence");
            sequence2.SetId(0xfe);
            precondition.AddChild(sequence2);
            Condition_bt_WrapperAI_Organ_CrystalWithAttack_node255 _node4 = new Condition_bt_WrapperAI_Organ_CrystalWithAttack_node255();
            _node4.SetClassNameString("Condition");
            _node4.SetId(0xff);
            sequence2.AddChild(_node4);
            sequence2.SetHasEvents(sequence2.HasEvents() | _node4.HasEvents());
            Action_bt_WrapperAI_Organ_CrystalWithAttack_node256 _node5 = new Action_bt_WrapperAI_Organ_CrystalWithAttack_node256();
            _node5.SetClassNameString("Action");
            _node5.SetId(0x100);
            sequence2.AddChild(_node5);
            sequence2.SetHasEvents(sequence2.HasEvents() | _node5.HasEvents());
            Action_bt_WrapperAI_Organ_CrystalWithAttack_node260 _node6 = new Action_bt_WrapperAI_Organ_CrystalWithAttack_node260();
            _node6.SetClassNameString("Action");
            _node6.SetId(260);
            sequence2.AddChild(_node6);
            sequence2.SetHasEvents(sequence2.HasEvents() | _node6.HasEvents());
            precondition.SetHasEvents(precondition.HasEvents() | sequence2.HasEvents());
            False @false = new False();
            @false.SetClassNameString("False");
            @false.SetId(0xfc);
            precondition.AddChild(@false);
            precondition.SetHasEvents(precondition.HasEvents() | @false.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition.HasEvents());
            WithPrecondition precondition2 = new WithPrecondition();
            precondition2.SetClassNameString("WithPrecondition");
            precondition2.SetId(11);
            loop.AddChild(precondition2);
            Condition_bt_WrapperAI_Organ_CrystalWithAttack_node12 _node7 = new Condition_bt_WrapperAI_Organ_CrystalWithAttack_node12();
            _node7.SetClassNameString("Condition");
            _node7.SetId(12);
            precondition2.AddChild(_node7);
            precondition2.SetHasEvents(precondition2.HasEvents() | _node7.HasEvents());
            Sequence sequence3 = new Sequence();
            sequence3.SetClassNameString("Sequence");
            sequence3.SetId(13);
            precondition2.AddChild(sequence3);
            IfElse @else = new IfElse();
            @else.SetClassNameString("IfElse");
            @else.SetId(9);
            sequence3.AddChild(@else);
            Condition_bt_WrapperAI_Organ_CrystalWithAttack_node15 _node8 = new Condition_bt_WrapperAI_Organ_CrystalWithAttack_node15();
            _node8.SetClassNameString("Condition");
            _node8.SetId(15);
            @else.AddChild(_node8);
            @else.SetHasEvents(@else.HasEvents() | _node8.HasEvents());
            Sequence sequence4 = new Sequence();
            sequence4.SetClassNameString("Sequence");
            sequence4.SetId(0x11);
            @else.AddChild(sequence4);
            Action_bt_WrapperAI_Organ_CrystalWithAttack_node16 _node9 = new Action_bt_WrapperAI_Organ_CrystalWithAttack_node16();
            _node9.SetClassNameString("Action");
            _node9.SetId(0x10);
            sequence4.AddChild(_node9);
            sequence4.SetHasEvents(sequence4.HasEvents() | _node9.HasEvents());
            Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node18 _node10 = new Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node18();
            _node10.SetClassNameString("Assignment");
            _node10.SetId(0x12);
            sequence4.AddChild(_node10);
            sequence4.SetHasEvents(sequence4.HasEvents() | _node10.HasEvents());
            @else.SetHasEvents(@else.HasEvents() | sequence4.HasEvents());
            Noop noop = new Noop();
            noop.SetClassNameString("Noop");
            noop.SetId(0x13);
            @else.AddChild(noop);
            @else.SetHasEvents(@else.HasEvents() | noop.HasEvents());
            sequence3.SetHasEvents(sequence3.HasEvents() | @else.HasEvents());
            Sequence sequence5 = new Sequence();
            sequence5.SetClassNameString("Sequence");
            sequence5.SetId(0x51);
            sequence3.AddChild(sequence5);
            IfElse else2 = new IfElse();
            else2.SetClassNameString("IfElse");
            else2.SetId(10);
            sequence5.AddChild(else2);
            And and = new And();
            and.SetClassNameString("And");
            and.SetId(0x15);
            else2.AddChild(and);
            Condition_bt_WrapperAI_Organ_CrystalWithAttack_node20 _node11 = new Condition_bt_WrapperAI_Organ_CrystalWithAttack_node20();
            _node11.SetClassNameString("Condition");
            _node11.SetId(20);
            and.AddChild(_node11);
            and.SetHasEvents(and.HasEvents() | _node11.HasEvents());
            Condition_bt_WrapperAI_Organ_CrystalWithAttack_node22 _node12 = new Condition_bt_WrapperAI_Organ_CrystalWithAttack_node22();
            _node12.SetClassNameString("Condition");
            _node12.SetId(0x16);
            and.AddChild(_node12);
            and.SetHasEvents(and.HasEvents() | _node12.HasEvents());
            else2.SetHasEvents(else2.HasEvents() | and.HasEvents());
            Noop noop2 = new Noop();
            noop2.SetClassNameString("Noop");
            noop2.SetId(0x17);
            else2.AddChild(noop2);
            else2.SetHasEvents(else2.HasEvents() | noop2.HasEvents());
            Sequence sequence6 = new Sequence();
            sequence6.SetClassNameString("Sequence");
            sequence6.SetId(0x18);
            else2.AddChild(sequence6);
            Action_bt_WrapperAI_Organ_CrystalWithAttack_node25 _node13 = new Action_bt_WrapperAI_Organ_CrystalWithAttack_node25();
            _node13.SetClassNameString("Action");
            _node13.SetId(0x19);
            sequence6.AddChild(_node13);
            sequence6.SetHasEvents(sequence6.HasEvents() | _node13.HasEvents());
            Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node83 _node14 = new Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node83();
            _node14.SetClassNameString("Assignment");
            _node14.SetId(0x53);
            sequence6.AddChild(_node14);
            sequence6.SetHasEvents(sequence6.HasEvents() | _node14.HasEvents());
            else2.SetHasEvents(else2.HasEvents() | sequence6.HasEvents());
            sequence5.SetHasEvents(sequence5.HasEvents() | else2.HasEvents());
            IfElse else3 = new IfElse();
            else3.SetClassNameString("IfElse");
            else3.SetId(0x54);
            sequence5.AddChild(else3);
            Condition_bt_WrapperAI_Organ_CrystalWithAttack_node85 _node15 = new Condition_bt_WrapperAI_Organ_CrystalWithAttack_node85();
            _node15.SetClassNameString("Condition");
            _node15.SetId(0x55);
            else3.AddChild(_node15);
            else3.SetHasEvents(else3.HasEvents() | _node15.HasEvents());
            Sequence sequence7 = new Sequence();
            sequence7.SetClassNameString("Sequence");
            sequence7.SetId(0x56);
            else3.AddChild(sequence7);
            Action_bt_WrapperAI_Organ_CrystalWithAttack_node140 _node16 = new Action_bt_WrapperAI_Organ_CrystalWithAttack_node140();
            _node16.SetClassNameString("Action");
            _node16.SetId(140);
            sequence7.AddChild(_node16);
            sequence7.SetHasEvents(sequence7.HasEvents() | _node16.HasEvents());
            Action_bt_WrapperAI_Organ_CrystalWithAttack_node87 _node17 = new Action_bt_WrapperAI_Organ_CrystalWithAttack_node87();
            _node17.SetClassNameString("Action");
            _node17.SetId(0x57);
            sequence7.AddChild(_node17);
            sequence7.SetHasEvents(sequence7.HasEvents() | _node17.HasEvents());
            Action_bt_WrapperAI_Organ_CrystalWithAttack_node88 _node18 = new Action_bt_WrapperAI_Organ_CrystalWithAttack_node88();
            _node18.SetClassNameString("Action");
            _node18.SetId(0x58);
            sequence7.AddChild(_node18);
            sequence7.SetHasEvents(sequence7.HasEvents() | _node18.HasEvents());
            Action_bt_WrapperAI_Organ_CrystalWithAttack_node91 _node19 = new Action_bt_WrapperAI_Organ_CrystalWithAttack_node91();
            _node19.SetClassNameString("Action");
            _node19.SetId(0x5b);
            sequence7.AddChild(_node19);
            sequence7.SetHasEvents(sequence7.HasEvents() | _node19.HasEvents());
            DecoratorLoopUntil_bt_WrapperAI_Organ_CrystalWithAttack_node92 _node20 = new DecoratorLoopUntil_bt_WrapperAI_Organ_CrystalWithAttack_node92();
            _node20.SetClassNameString("DecoratorLoopUntil");
            _node20.SetId(0x5c);
            sequence7.AddChild(_node20);
            Condition_bt_WrapperAI_Organ_CrystalWithAttack_node93 _node21 = new Condition_bt_WrapperAI_Organ_CrystalWithAttack_node93();
            _node21.SetClassNameString("Condition");
            _node21.SetId(0x5d);
            _node20.AddChild(_node21);
            _node20.SetHasEvents(_node20.HasEvents() | _node21.HasEvents());
            sequence7.SetHasEvents(sequence7.HasEvents() | _node20.HasEvents());
            else3.SetHasEvents(else3.HasEvents() | sequence7.HasEvents());
            WaitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node5 _node22 = new WaitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node5();
            _node22.SetClassNameString("WaitFrames");
            _node22.SetId(5);
            else3.AddChild(_node22);
            else3.SetHasEvents(else3.HasEvents() | _node22.HasEvents());
            sequence5.SetHasEvents(sequence5.HasEvents() | else3.HasEvents());
            sequence3.SetHasEvents(sequence3.HasEvents() | sequence5.HasEvents());
            precondition2.SetHasEvents(precondition2.HasEvents() | sequence3.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition2.HasEvents());
            WithPrecondition precondition3 = new WithPrecondition();
            precondition3.SetClassNameString("WithPrecondition");
            precondition3.SetId(2);
            loop.AddChild(precondition3);
            Condition_bt_WrapperAI_Organ_CrystalWithAttack_node3 _node23 = new Condition_bt_WrapperAI_Organ_CrystalWithAttack_node3();
            _node23.SetClassNameString("Condition");
            _node23.SetId(3);
            precondition3.AddChild(_node23);
            precondition3.SetHasEvents(precondition3.HasEvents() | _node23.HasEvents());
            Sequence sequence8 = new Sequence();
            sequence8.SetClassNameString("Sequence");
            sequence8.SetId(6);
            precondition3.AddChild(sequence8);
            Action_bt_WrapperAI_Organ_CrystalWithAttack_node4 _node24 = new Action_bt_WrapperAI_Organ_CrystalWithAttack_node4();
            _node24.SetClassNameString("Action");
            _node24.SetId(4);
            sequence8.AddChild(_node24);
            sequence8.SetHasEvents(sequence8.HasEvents() | _node24.HasEvents());
            DecoratorLoop_bt_WrapperAI_Organ_CrystalWithAttack_node7 _node25 = new DecoratorLoop_bt_WrapperAI_Organ_CrystalWithAttack_node7();
            _node25.SetClassNameString("DecoratorLoop");
            _node25.SetId(7);
            sequence8.AddChild(_node25);
            Noop noop3 = new Noop();
            noop3.SetClassNameString("Noop");
            noop3.SetId(8);
            _node25.AddChild(noop3);
            _node25.SetHasEvents(_node25.HasEvents() | noop3.HasEvents());
            sequence8.SetHasEvents(sequence8.HasEvents() | _node25.HasEvents());
            precondition3.SetHasEvents(precondition3.HasEvents() | sequence8.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition3.HasEvents());
            _node3.SetHasEvents(_node3.HasEvents() | loop.HasEvents());
            Sequence sequence9 = new Sequence();
            sequence9.SetClassNameString("Sequence");
            sequence9.SetId(0x4b);
            _node3.AddChild(sequence9);
            Action_bt_WrapperAI_Organ_CrystalWithAttack_node30 _node26 = new Action_bt_WrapperAI_Organ_CrystalWithAttack_node30();
            _node26.SetClassNameString("Action");
            _node26.SetId(30);
            sequence9.AddChild(_node26);
            sequence9.SetHasEvents(sequence9.HasEvents() | _node26.HasEvents());
            Condition_bt_WrapperAI_Organ_CrystalWithAttack_node97 _node27 = new Condition_bt_WrapperAI_Organ_CrystalWithAttack_node97();
            _node27.SetClassNameString("Condition");
            _node27.SetId(0x61);
            sequence9.AddChild(_node27);
            sequence9.SetHasEvents(sequence9.HasEvents() | _node27.HasEvents());
            SelectorLoop loop2 = new SelectorLoop();
            loop2.SetClassNameString("SelectorLoop");
            loop2.SetId(80);
            sequence9.AddChild(loop2);
            WithPrecondition precondition4 = new WithPrecondition();
            precondition4.SetClassNameString("WithPrecondition");
            precondition4.SetId(0x59);
            loop2.AddChild(precondition4);
            Sequence sequence10 = new Sequence();
            sequence10.SetClassNameString("Sequence");
            sequence10.SetId(90);
            precondition4.AddChild(sequence10);
            Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node76 _node28 = new Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node76();
            _node28.SetClassNameString("Assignment");
            _node28.SetId(0x4c);
            sequence10.AddChild(_node28);
            sequence10.SetHasEvents(sequence10.HasEvents() | _node28.HasEvents());
            Condition_bt_WrapperAI_Organ_CrystalWithAttack_node77 _node29 = new Condition_bt_WrapperAI_Organ_CrystalWithAttack_node77();
            _node29.SetClassNameString("Condition");
            _node29.SetId(0x4d);
            sequence10.AddChild(_node29);
            sequence10.SetHasEvents(sequence10.HasEvents() | _node29.HasEvents());
            precondition4.SetHasEvents(precondition4.HasEvents() | sequence10.HasEvents());
            Sequence sequence11 = new Sequence();
            sequence11.SetClassNameString("Sequence");
            sequence11.SetId(0x5e);
            precondition4.AddChild(sequence11);
            Action_bt_WrapperAI_Organ_CrystalWithAttack_node78 _node30 = new Action_bt_WrapperAI_Organ_CrystalWithAttack_node78();
            _node30.SetClassNameString("Action");
            _node30.SetId(0x4e);
            sequence11.AddChild(_node30);
            sequence11.SetHasEvents(sequence11.HasEvents() | _node30.HasEvents());
            Compute_bt_WrapperAI_Organ_CrystalWithAttack_node31 _node31 = new Compute_bt_WrapperAI_Organ_CrystalWithAttack_node31();
            _node31.SetClassNameString("Compute");
            _node31.SetId(0x1f);
            sequence11.AddChild(_node31);
            sequence11.SetHasEvents(sequence11.HasEvents() | _node31.HasEvents());
            Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node39 _node32 = new Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node39();
            _node32.SetClassNameString("Assignment");
            _node32.SetId(0x27);
            sequence11.AddChild(_node32);
            sequence11.SetHasEvents(sequence11.HasEvents() | _node32.HasEvents());
            WaitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node79 _node33 = new WaitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node79();
            _node33.SetClassNameString("WaitFrames");
            _node33.SetId(0x4f);
            sequence11.AddChild(_node33);
            sequence11.SetHasEvents(sequence11.HasEvents() | _node33.HasEvents());
            precondition4.SetHasEvents(precondition4.HasEvents() | sequence11.HasEvents());
            loop2.SetHasEvents(loop2.HasEvents() | precondition4.HasEvents());
            WithPrecondition precondition5 = new WithPrecondition();
            precondition5.SetClassNameString("WithPrecondition");
            precondition5.SetId(40);
            loop2.AddChild(precondition5);
            Action_bt_WrapperAI_Organ_CrystalWithAttack_node29 _node34 = new Action_bt_WrapperAI_Organ_CrystalWithAttack_node29();
            _node34.SetClassNameString("Action");
            _node34.SetId(0x1d);
            precondition5.AddChild(_node34);
            precondition5.SetHasEvents(precondition5.HasEvents() | _node34.HasEvents());
            Sequence sequence12 = new Sequence();
            sequence12.SetClassNameString("Sequence");
            sequence12.SetId(0x4a);
            precondition5.AddChild(sequence12);
            Condition_bt_WrapperAI_Organ_CrystalWithAttack_node98 _node35 = new Condition_bt_WrapperAI_Organ_CrystalWithAttack_node98();
            _node35.SetClassNameString("Condition");
            _node35.SetId(0x62);
            sequence12.AddChild(_node35);
            sequence12.SetHasEvents(sequence12.HasEvents() | _node35.HasEvents());
            Compute_bt_WrapperAI_Organ_CrystalWithAttack_node99 _node36 = new Compute_bt_WrapperAI_Organ_CrystalWithAttack_node99();
            _node36.SetClassNameString("Compute");
            _node36.SetId(0x63);
            sequence12.AddChild(_node36);
            sequence12.SetHasEvents(sequence12.HasEvents() | _node36.HasEvents());
            Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node100 _node37 = new Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node100();
            _node37.SetClassNameString("Assignment");
            _node37.SetId(100);
            sequence12.AddChild(_node37);
            sequence12.SetHasEvents(sequence12.HasEvents() | _node37.HasEvents());
            SelectorProbability_bt_WrapperAI_Organ_CrystalWithAttack_node101 _node38 = new SelectorProbability_bt_WrapperAI_Organ_CrystalWithAttack_node101();
            _node38.SetClassNameString("SelectorProbability");
            _node38.SetId(0x65);
            sequence12.AddChild(_node38);
            DecoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node102 pBehavior = new DecoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node102();
            pBehavior.SetClassNameString("DecoratorWeight");
            pBehavior.SetId(0x66);
            _node38.AddChild(pBehavior);
            Sequence sequence13 = new Sequence();
            sequence13.SetClassNameString("Sequence");
            sequence13.SetId(0x67);
            pBehavior.AddChild(sequence13);
            Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node104 _node40 = new Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node104();
            _node40.SetClassNameString("Assignment");
            _node40.SetId(0x68);
            sequence13.AddChild(_node40);
            sequence13.SetHasEvents(sequence13.HasEvents() | _node40.HasEvents());
            Condition_bt_WrapperAI_Organ_CrystalWithAttack_node105 _node41 = new Condition_bt_WrapperAI_Organ_CrystalWithAttack_node105();
            _node41.SetClassNameString("Condition");
            _node41.SetId(0x69);
            sequence13.AddChild(_node41);
            sequence13.SetHasEvents(sequence13.HasEvents() | _node41.HasEvents());
            Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node106 _node42 = new Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node106();
            _node42.SetClassNameString("Assignment");
            _node42.SetId(0x6a);
            sequence13.AddChild(_node42);
            sequence13.SetHasEvents(sequence13.HasEvents() | _node42.HasEvents());
            Condition_bt_WrapperAI_Organ_CrystalWithAttack_node107 _node43 = new Condition_bt_WrapperAI_Organ_CrystalWithAttack_node107();
            _node43.SetClassNameString("Condition");
            _node43.SetId(0x6b);
            sequence13.AddChild(_node43);
            sequence13.SetHasEvents(sequence13.HasEvents() | _node43.HasEvents());
            Action_bt_WrapperAI_Organ_CrystalWithAttack_node108 _node44 = new Action_bt_WrapperAI_Organ_CrystalWithAttack_node108();
            _node44.SetClassNameString("Action");
            _node44.SetId(0x6c);
            sequence13.AddChild(_node44);
            sequence13.SetHasEvents(sequence13.HasEvents() | _node44.HasEvents());
            WaitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node109 _node45 = new WaitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node109();
            _node45.SetClassNameString("WaitFrames");
            _node45.SetId(0x6d);
            sequence13.AddChild(_node45);
            sequence13.SetHasEvents(sequence13.HasEvents() | _node45.HasEvents());
            pBehavior.SetHasEvents(pBehavior.HasEvents() | sequence13.HasEvents());
            _node38.SetHasEvents(_node38.HasEvents() | pBehavior.HasEvents());
            DecoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node110 _node46 = new DecoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node110();
            _node46.SetClassNameString("DecoratorWeight");
            _node46.SetId(110);
            _node38.AddChild(_node46);
            Sequence sequence14 = new Sequence();
            sequence14.SetClassNameString("Sequence");
            sequence14.SetId(0x6f);
            _node46.AddChild(sequence14);
            Condition_bt_WrapperAI_Organ_CrystalWithAttack_node32 _node47 = new Condition_bt_WrapperAI_Organ_CrystalWithAttack_node32();
            _node47.SetClassNameString("Condition");
            _node47.SetId(0x20);
            sequence14.AddChild(_node47);
            sequence14.SetHasEvents(sequence14.HasEvents() | _node47.HasEvents());
            Condition_bt_WrapperAI_Organ_CrystalWithAttack_node112 _node48 = new Condition_bt_WrapperAI_Organ_CrystalWithAttack_node112();
            _node48.SetClassNameString("Condition");
            _node48.SetId(0x70);
            sequence14.AddChild(_node48);
            sequence14.SetHasEvents(sequence14.HasEvents() | _node48.HasEvents());
            Condition_bt_WrapperAI_Organ_CrystalWithAttack_node113 _node49 = new Condition_bt_WrapperAI_Organ_CrystalWithAttack_node113();
            _node49.SetClassNameString("Condition");
            _node49.SetId(0x71);
            sequence14.AddChild(_node49);
            sequence14.SetHasEvents(sequence14.HasEvents() | _node49.HasEvents());
            Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node114 _node50 = new Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node114();
            _node50.SetClassNameString("Assignment");
            _node50.SetId(0x72);
            sequence14.AddChild(_node50);
            sequence14.SetHasEvents(sequence14.HasEvents() | _node50.HasEvents());
            Condition_bt_WrapperAI_Organ_CrystalWithAttack_node115 _node51 = new Condition_bt_WrapperAI_Organ_CrystalWithAttack_node115();
            _node51.SetClassNameString("Condition");
            _node51.SetId(0x73);
            sequence14.AddChild(_node51);
            sequence14.SetHasEvents(sequence14.HasEvents() | _node51.HasEvents());
            Action_bt_WrapperAI_Organ_CrystalWithAttack_node116 _node52 = new Action_bt_WrapperAI_Organ_CrystalWithAttack_node116();
            _node52.SetClassNameString("Action");
            _node52.SetId(0x74);
            sequence14.AddChild(_node52);
            sequence14.SetHasEvents(sequence14.HasEvents() | _node52.HasEvents());
            WaitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node117 _node53 = new WaitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node117();
            _node53.SetClassNameString("WaitFrames");
            _node53.SetId(0x75);
            sequence14.AddChild(_node53);
            sequence14.SetHasEvents(sequence14.HasEvents() | _node53.HasEvents());
            _node46.SetHasEvents(_node46.HasEvents() | sequence14.HasEvents());
            _node38.SetHasEvents(_node38.HasEvents() | _node46.HasEvents());
            DecoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node118 _node54 = new DecoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node118();
            _node54.SetClassNameString("DecoratorWeight");
            _node54.SetId(0x76);
            _node38.AddChild(_node54);
            Sequence sequence15 = new Sequence();
            sequence15.SetClassNameString("Sequence");
            sequence15.SetId(0x77);
            _node54.AddChild(sequence15);
            Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node120 _node55 = new Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node120();
            _node55.SetClassNameString("Assignment");
            _node55.SetId(120);
            sequence15.AddChild(_node55);
            sequence15.SetHasEvents(sequence15.HasEvents() | _node55.HasEvents());
            Condition_bt_WrapperAI_Organ_CrystalWithAttack_node121 _node56 = new Condition_bt_WrapperAI_Organ_CrystalWithAttack_node121();
            _node56.SetClassNameString("Condition");
            _node56.SetId(0x79);
            sequence15.AddChild(_node56);
            sequence15.SetHasEvents(sequence15.HasEvents() | _node56.HasEvents());
            Action_bt_WrapperAI_Organ_CrystalWithAttack_node122 _node57 = new Action_bt_WrapperAI_Organ_CrystalWithAttack_node122();
            _node57.SetClassNameString("Action");
            _node57.SetId(0x7a);
            sequence15.AddChild(_node57);
            sequence15.SetHasEvents(sequence15.HasEvents() | _node57.HasEvents());
            WaitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node123 _node58 = new WaitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node123();
            _node58.SetClassNameString("WaitFrames");
            _node58.SetId(0x7b);
            sequence15.AddChild(_node58);
            sequence15.SetHasEvents(sequence15.HasEvents() | _node58.HasEvents());
            _node54.SetHasEvents(_node54.HasEvents() | sequence15.HasEvents());
            _node38.SetHasEvents(_node38.HasEvents() | _node54.HasEvents());
            DecoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node124 _node59 = new DecoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node124();
            _node59.SetClassNameString("DecoratorWeight");
            _node59.SetId(0x7c);
            _node38.AddChild(_node59);
            Sequence sequence16 = new Sequence();
            sequence16.SetClassNameString("Sequence");
            sequence16.SetId(0x7d);
            _node59.AddChild(sequence16);
            Condition_bt_WrapperAI_Organ_CrystalWithAttack_node126 _node60 = new Condition_bt_WrapperAI_Organ_CrystalWithAttack_node126();
            _node60.SetClassNameString("Condition");
            _node60.SetId(0x7e);
            sequence16.AddChild(_node60);
            sequence16.SetHasEvents(sequence16.HasEvents() | _node60.HasEvents());
            Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node127 _node61 = new Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node127();
            _node61.SetClassNameString("Assignment");
            _node61.SetId(0x7f);
            sequence16.AddChild(_node61);
            sequence16.SetHasEvents(sequence16.HasEvents() | _node61.HasEvents());
            Condition_bt_WrapperAI_Organ_CrystalWithAttack_node128 _node62 = new Condition_bt_WrapperAI_Organ_CrystalWithAttack_node128();
            _node62.SetClassNameString("Condition");
            _node62.SetId(0x80);
            sequence16.AddChild(_node62);
            sequence16.SetHasEvents(sequence16.HasEvents() | _node62.HasEvents());
            Action_bt_WrapperAI_Organ_CrystalWithAttack_node129 _node63 = new Action_bt_WrapperAI_Organ_CrystalWithAttack_node129();
            _node63.SetClassNameString("Action");
            _node63.SetId(0x81);
            sequence16.AddChild(_node63);
            sequence16.SetHasEvents(sequence16.HasEvents() | _node63.HasEvents());
            Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node130 _node64 = new Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node130();
            _node64.SetClassNameString("Assignment");
            _node64.SetId(130);
            sequence16.AddChild(_node64);
            sequence16.SetHasEvents(sequence16.HasEvents() | _node64.HasEvents());
            Action_bt_WrapperAI_Organ_CrystalWithAttack_node131 _node65 = new Action_bt_WrapperAI_Organ_CrystalWithAttack_node131();
            _node65.SetClassNameString("Action");
            _node65.SetId(0x83);
            sequence16.AddChild(_node65);
            sequence16.SetHasEvents(sequence16.HasEvents() | _node65.HasEvents());
            Compute_bt_WrapperAI_Organ_CrystalWithAttack_node132 _node66 = new Compute_bt_WrapperAI_Organ_CrystalWithAttack_node132();
            _node66.SetClassNameString("Compute");
            _node66.SetId(0x84);
            sequence16.AddChild(_node66);
            sequence16.SetHasEvents(sequence16.HasEvents() | _node66.HasEvents());
            Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node133 _node67 = new Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node133();
            _node67.SetClassNameString("Assignment");
            _node67.SetId(0x85);
            sequence16.AddChild(_node67);
            sequence16.SetHasEvents(sequence16.HasEvents() | _node67.HasEvents());
            WaitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node134 _node68 = new WaitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node134();
            _node68.SetClassNameString("WaitFrames");
            _node68.SetId(0x86);
            sequence16.AddChild(_node68);
            sequence16.SetHasEvents(sequence16.HasEvents() | _node68.HasEvents());
            Action_bt_WrapperAI_Organ_CrystalWithAttack_node135 _node69 = new Action_bt_WrapperAI_Organ_CrystalWithAttack_node135();
            _node69.SetClassNameString("Action");
            _node69.SetId(0x87);
            sequence16.AddChild(_node69);
            sequence16.SetHasEvents(sequence16.HasEvents() | _node69.HasEvents());
            WaitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node136 _node70 = new WaitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node136();
            _node70.SetClassNameString("WaitFrames");
            _node70.SetId(0x88);
            sequence16.AddChild(_node70);
            sequence16.SetHasEvents(sequence16.HasEvents() | _node70.HasEvents());
            _node59.SetHasEvents(_node59.HasEvents() | sequence16.HasEvents());
            _node38.SetHasEvents(_node38.HasEvents() | _node59.HasEvents());
            DecoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node137 _node71 = new DecoratorWeight_bt_WrapperAI_Organ_CrystalWithAttack_node137();
            _node71.SetClassNameString("DecoratorWeight");
            _node71.SetId(0x89);
            _node38.AddChild(_node71);
            Noop noop4 = new Noop();
            noop4.SetClassNameString("Noop");
            noop4.SetId(0x8a);
            _node71.AddChild(noop4);
            _node71.SetHasEvents(_node71.HasEvents() | noop4.HasEvents());
            _node38.SetHasEvents(_node38.HasEvents() | _node71.HasEvents());
            sequence12.SetHasEvents(sequence12.HasEvents() | _node38.HasEvents());
            WaitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node139 _node72 = new WaitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node139();
            _node72.SetClassNameString("WaitFrames");
            _node72.SetId(0x8b);
            sequence12.AddChild(_node72);
            sequence12.SetHasEvents(sequence12.HasEvents() | _node72.HasEvents());
            precondition5.SetHasEvents(precondition5.HasEvents() | sequence12.HasEvents());
            loop2.SetHasEvents(loop2.HasEvents() | precondition5.HasEvents());
            sequence9.SetHasEvents(sequence9.HasEvents() | loop2.HasEvents());
            _node3.SetHasEvents(_node3.HasEvents() | sequence9.HasEvents());
            _node2.SetHasEvents(_node2.HasEvents() | _node3.HasEvents());
            pChild.SetHasEvents(pChild.HasEvents() | _node2.HasEvents());
            bt.SetHasEvents(bt.HasEvents() | pChild.HasEvents());
            return true;
        }
    }
}

